Makefile, pyproject.toml, requirements-dev.txt
Use the pylint_fixme_info plugin to make TODO/FIXME messages informational
rather than warnings or errors. This allows us to remove the --fail-under
switch when running pylint on CI.
-----
=> tests: configure pylint to issue fixme-info

craft_parts/state_manager/pull_state.py, craft_parts/state_manager/step_state.py, requirements.txt, tests/unit/state_manager/conftest.py, tests/unit/state_manager/test_pull_state.py, tests/unit/state_manager/test_step_state.py
The PullState class holds context information collected when the
pull step runs for a part.
This PR partially replaces PR #12.
-----
=> states: add pull state class

craft_parts/state_manager/build_state.py, craft_parts/state_manager/pull_state.py, tests/unit/state_manager/test_build_state.py, tests/unit/state_manager/test_pull_state.py
The BuildState class holds context information collected when the
build step runs for a part.
This PR partially replaces PR #12.
-----
=> states: add build state class

craft_parts/state_manager/stage_state.py, tests/unit/state_manager/test_stage_state.py
The StageState class holds context information collected when the
stage step runs for a part.
This PR partially replaces PR #12.
-----
=> states: add stage state class

craft_parts/state_manager/prime_state.py, craft_parts/state_manager/states.py, pyproject.toml, tests/unit/state_manager/test_prime_state.py, tests/unit/state_manager/test_states.py
The PrimeState class holds context information collected when the
prime step runs for a part. Also add a state loader helper that
reads persistent state based on part and state, unmarshaling data
into an appropriate state object.
This PR replaces PR #12.
-----
=> states: add prime state class and state loader

craft_parts/state_manager/state_manager.py, tests/unit/state_manager/test_state_manager.py
Wrap step states with metadata used in lifecycle action sequencing,
and implement a dictionary-backed database of wrapped states indexed
by part name and step.
-----
=> states: add state metadata and ephemeral state manager

craft_parts/infos.py, craft_parts/lifecycle_manager.py, tests/unit/test_infos.py, tests/unit/test_lifecycle_manager.py
Don't implement support for plugin API versions until we have a practical
use for that feature. It adds unnecessary complexity at this point.
-----
=> infos: remove plugin version from project properties

craft_parts/state_manager/__init__.py, craft_parts/state_manager/state_manager.py, tests/unit/state_manager/test_state_manager.py
The State Manager initializes and keeps track of states for each part
and step, telling the lifecycle sequencer whether a step should run
for any given part.
This PR starts the implementation of `StateManager`, more methods
will be added in future PRs.
-----
=> states: add stage manager class

craft_parts/infos.py, tests/unit/test_infos.py, tests/unit/test_parts.py
The part information class holds information to be passed to pre and
post-step callbacks for user environment setup.
-----
=> infos: add part information class

craft_parts/state_manager/reports.py, craft_parts/state_manager/state_manager.py, craft_parts/utils/formatting_utils.py, tests/unit/state_manager/test_reports.py, tests/unit/state_manager/test_state_manager.py, tests/unit/utils/test_formatting_utils.py
A part step is considered outdated if one of previous steps ran more
recently, or if logic in the source handler for that part says so.
This change implements the step execution order verification,
leaving source checks to be added later (after source handlers are
added to the codebase).
-----
=> states: add outdated step verification

craft_parts/state_manager/state_manager.py, tests/unit/state_manager/test_state_manager.py
Lifecycle planning requires in-memory states to be cleaned or marked
as recently updated. This change adds the necessary methods to obtain
these results.
-----
=> states: add management methods to refresh and clean steps

craft_parts/infos.py, craft_parts/state_manager/reports.py, craft_parts/state_manager/state_manager.py, pyproject.toml, tests/unit/state_manager/test_reports.py, tests/unit/state_manager/test_state_manager.py
A part step is considered dirty if one of its state properties
or options have changed, or if one of its dependencies should run.
-----
=> states: add dirty step verification

craft_parts/sources/__init__.py, craft_parts/sources/checksum.py, craft_parts/sources/errors.py, craft_parts/utils/file_utils.py, tests/unit/sources/test_checksum.py, tests/unit/sources/test_errors.py, tests/unit/utils/test_file_utils.py
Add support to computing file checksum to validate the source-checksum
part property.
-----
=> sources: add support for source checksum

craft_parts/plugins/__init__.py, craft_parts/plugins/base.py, craft_parts/plugins/properties.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_properties.py
The plugin subsystem defines how part sources will be built, using
optional plugin-specific properties defined in the part specification.
-----
=> plugins: add plugin and plugin properties base classes

craft_parts/sequencer.py, craft_parts/state_manager/states.py, tests/unit/test_sequencer.py
Lifecycle planning requires updating step states and emmiting the
appropriate actions to be executed later. This is done in different
ways depending if we're running a step for the first time, re-running
it, or updating it. This change adds the appropriate handlers for
each case.
-----
=> sequencer: handle step run, rerun and update

craft_parts/plugins/nil_plugin.py, tests/unit/plugins/test_nil_plugin.py
The nil plugin is used to handle parts with no source.
-----
=> plugins: add the nil plugin

craft_parts/sources/cache.py, requirements.txt, tests/conftest.py, tests/unit/sources/test_cache.py
Sources with the `source-checksum` property are cached so they won't
be re-downloaded. This change implements a simple file cache that
stores such files under their digest key.
-----
=> sources: add simple file cache

tests/unit/plugins/test_base.py, tests/unit/test_sequencer.py, tests/unit/utils/test_file_utils.py
Minor changes to address pylint warnings in tests.
-----
=> tests: address pylint issues

craft_parts/utils/os_utils.py, craft_parts/utils/url_utils.py, requirements-dev.txt, requirements.txt, tests/unit/utils/test_os_utils.py, tests/unit/utils/test_url_utils.py
File sources need to parse and download files from given URLs. Add such
helpers to `url_utils` using code from snapcraft.
**Note to reviewers:** Only minimal testing was added -- the helpers will be
refactored later to use the standard messages library.
-----
=> utils: add url parsing and downloading helpers

craft_parts/plugins/base.py, craft_parts/plugins/make_plugin.py, tests/integration/plugins/test_make.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_make_plugin.py
The make plugin is useful to build make-based parts.
-----
=> plugins: add make plugin

craft_parts/plugins/autotools_plugin.py, craft_parts/plugins/make_plugin.py, tests/integration/plugins/test_autotools.py, tests/unit/plugins/test_autotools_plugin.py
The autotools plugin is used for parts using the autotools `./configure` script.
-----
=> plugins: add autotools plugin

craft_parts/errors.py, craft_parts/xattrs.py, tests/unit/test_errors.py, tests/unit/test_xattrs.py
Extended attributes are used to track the origin of primed files.
-----
=> metadata: add support for extended attributes

craft_parts/sources/local_source.py, craft_parts/sources/sources.py, tests/unit/sources/test_local_source.py
The local source handler implements pull and update for sources that
are already in the host filesystem.
Note: the source handler implementation and accompanying tests are a
direct port of the corresponding files in snapcraft and may be revisited and
refactored in the future.
-----
=> sources: add the local source handler

craft_parts/plugins/__init__.py, craft_parts/plugins/plugins.py, tests/unit/plugins/test_plugins.py
Application-defined plugins must be registered to be recognized by
Craft Parts. This change implements the plugin registry and helpers
to register, unregister, and retrieve plugin classes and instances.
-----
=> plugins: add plugin registry and management helpers

craft_parts/errors.py, craft_parts/lifecycle_manager.py, craft_parts/parts.py, craft_parts/plugins/base.py, tests/unit/test_errors.py, tests/unit/test_lifecycle_manager.py
Plugin properties are specified along part properties and prefixed by
the plugin name. Validate and unmarshal properties and assign them
to the corresponding part.
-----
=> parts: unmarshal plugin properties

craft_parts/state_manager/step_state.py, craft_parts/utils/os_utils.py, tests/unit/state_manager/test_state_manager.py, tests/unit/utils/test_os_utils.py
Hosts with low timer resolution may create files with identical
timestamps if files are written at a rate higher than its tick
rate. Prevent that by enforcing a minimum time interval between
subsequent state writes.
-----
=> states: ensure minimum interval between state writes

craft_parts/packages/__init__.py, craft_parts/packages/base.py, tests/unit/packages/test_base.py
Execution of the parts lifecycle requires packages to be installed on
the build host and onto the stage tree. "Packages" is derived from
snapcraft's "repo", minus repository management, plus minor refactoring
including changes to split normalization from the base class to improve
code readability.
-----
=> packages: add base and dummy repository classes

craft_parts/packages/apt_cache.py, craft_parts/packages/base.py, craft_parts/packages/errors.py, craft_parts/utils/os_utils.py, requirements.txt, tests/unit/packages/test_apt_cache.py, tests/unit/packages/test_errors.py
Add infrastructure to retrieve packages using apt.
-----
=> packages: add support to apt cache operations

craft_parts/errors.py, craft_parts/utils/os_utils.py, pyproject.toml, tests/unit/test_errors.py, tests/unit/utils/test_os_utils.py
The `os-release` file contains operating system identification data.
Add helpers to obtain information from this file, raising errors
if data could not be retrieved.
This implementation and accompanying tests are a direct port from
`snapcraft.internal.os_release`.
-----
=> utils: add helpers to read os-release entries

tests/conftest.py, tests/fake_servers.py, tests/fake_snapd.py
The fake snapd fixture will be used to test snap package handling
in `craft-parts.packages`.
-----
=> tests: add fake snapd fixture

craft_parts/packages/errors.py, tests/unit/packages/test_errors.py
Add exception classes for snap handling errors. These will be used
in `craft_parts.packages.snaps`.
-----
=> packages: add snap-related exceptions

craft_parts/packages/base.py, craft_parts/packages/deb.py, craft_parts/packages/deb_package.py, craft_parts/packages/errors.py, tests/unit/packages/test_deb.py, tests/unit/packages/test_deb_package.py, tests/unit/packages/test_errors.py
The Ubuntu deb repository support adds the mechanism to refresh
package lists, fetch and unpack stage packages, and install build
packages.
-----
=> packages: add deb support

craft_parts/packages/snaps.py, requirements.txt, tests/conftest.py, tests/fake_snap_command.py, tests/unit/packages/test_snaps.py
Snap packages can be listed in the parts specification as stage snaps
or build snaps. This change implements the mechanism to handle snap
download and installation.
-----
=> packages: add snap package support

craft_parts/sources/__init__.py, craft_parts/sources/base.py, craft_parts/sources/errors.py, craft_parts/sources/sources.py, craft_parts/sources/tar_source.py, craft_parts/state_manager/state_manager.py, tests/unit/sources/test_errors.py, tests/unit/sources/test_sources.py, tests/unit/state_manager/test_state_manager.py
Provide calls to integrate source handlers with state manager and the
executor, and use it to check if sources are outdated during the
planning phase.
-----
=> sources: add source handler integration

craft_parts/errors.py, craft_parts/executor/__init__.py, craft_parts/executor/filesets.py, tests/unit/executor/test_filesets.py, tests/unit/test_errors.py
Filesets are filters used to include or exclude files that enter the
stage and prime filesystem areas. These filesets are defined under
the `stage` and `prime` properties in the parts specification.
Implementation of the filtering logic is ported from snapcraft.
-----
=> filesets: add fileset and file migration helpers

craft_parts/executor/environment.py, craft_parts/infos.py, craft_parts/utils/os_utils.py, tests/unit/executor/test_environment.py, tests/unit/test_infos.py, tests/unit/utils/test_os_utils.py
Generate a list of environment variables to be set at step execution,
using built-in, plugin, and user-defined variables from the part
specification.
Environment generation logic ported from snapcraft.
-----
=> executor: create environment for step execution

craft_parts/errors.py, craft_parts/executor/organize.py, tests/unit/executor/test_organize.py, tests/unit/test_errors.py
Parts can rearrange file locations according to a dictionary
provided in the `organize` property. This change implements
the file organization feature.
Organize logic and accompanying tests ported from Snapcraft.
-----
=> executor: add file organization support

tests/unit/sources/test_tar_source.py
Pylint 2.8.2 adds more warnings, address them.
-----
=> tests: update pylint and address new warnings

Makefile, craft_parts/errors.py, craft_parts/executor/collisions.py, pyproject.toml, requirements-dev.txt, tests/unit/executor/test_collisions.py, tests/unit/test_errors.py
Different parts must not stage files under the same name and with
different contents, it will result in staging error. This change adds
the functions that perform this verification.
Collision verification logic is ported from snapcraft.
-----
=> executor: add part file collision verification

craft_parts/executor/step_handler.py, craft_parts/parts.py, craft_parts/utils/file_utils.py, tests/unit/executor/test_step_handler.py, tests/unit/test_parts.py, tests/unit/utils/test_file_utils.py
The step handler takes care of the execution of a step, using either
a built-in set of actions to be taken, or executing a user-defined
script defined in the part specification. User-defined scripts may also
call the built-in handler for a step by invoking a control utility.
This class implements the built-in handlers and a FIFO-based mechanism
and API to be used by the external control utility to communicate with
the running instance.
The control API server is a direct port of the implementation used in
Snapcraft, and should be refactored later.
-----
=> executor: add the step handler

craft_parts/callbacks.py, craft_parts/errors.py, tests/integration/executor/test_callbacks.py, tests/unit/test_callbacks.py, tests/unit/test_errors.py
Callbacks are a mechanism to run application-specified functions at
certain points of the lifecycle execution, such as before or after
each step is processed, before the execution phase starts, or after
the execution phase ends.
-----
=> executor: add callbacks

craft_parts/utils/os_utils.py, tests/unit/utils/test_os_utils.py
Obtain information about the currently running system. This is a direct
port of the corresponding function in Snapcraft.
-----
=> utils: add call to retrieve system information

craft_parts/errors.py, tests/unit/test_errors.py
Define the errors that can be raised by the part handler during
action execution.
-----
=> executor: add errors raised in part handling

craft_parts/packages/platform.py, tests/unit/packages/test_platform.py
Determine the correct repository to use based on the host ID. This
implementation is a direct port from the corresponding function
in Snapcraft.
-----
=> packages: add host platform selection

craft_parts/__init__.py, craft_parts/errors.py, craft_parts/infos.py, craft_parts/plugins/base.py, craft_parts/plugins/plugins.py
Sphinx type hints are very sensitive to import cycles. In such case,
import only the module instead of classes/functions as explained in
the sphinx-autodoc-typehints documentation.
Also add missing parameter descriptions to docstrings.
-----
=> docs: fix sphinx doc generation and update docstrings

craft_parts/plugins/autotools_plugin.py, craft_parts/plugins/base.py, craft_parts/plugins/make_plugin.py, craft_parts/plugins/python_plugin.py, tests/unit/plugins/test_autotools_plugin.py, tests/unit/plugins/test_make_plugin.py, tests/unit/plugins/test_plugins.py, tests/unit/plugins/test_python_plugin.py, tests/unit/test_lifecycle_manager.py
Plugins may require certain part properties to be present, such as
"source". Let pydantic check these requirements during plugin property
validation instead of manually verifying their presence.
-----
=> plugins: check presence of required part properties (CRAFT-74)

craft_parts/executor/executor.py, craft_parts/lifecycle_manager.py, tests/integration/lifecycle/test_lifecycle.py
Add step and part cleaning and package list refresh methods to the
lifecycle manager.
-----
=> lifecycle: integrate executor clean and package list refresh (CRAFT-32)

tests/integration/plugins/test_dump.py
Make sure source files are installed and craft-parts work directories
are ignored.
-----
=> tests: add dump plugin integration test (CRAFT-70)

craft_parts/plugins/__init__.py, tests/integration/plugins/test_application_plugin.py
Applications can define and register plugins. Make sure application
plugins work.
-----
=> tests: add integration tests for application plugins (CRAFT-69)

craft_parts/ctl.py, craft_parts/executor/step_handler.py, craft_parts/infos.py, setup.py, tests/__init__.py, tests/integration/lifecycle/test_partsctl.py, tests/unit/test_ctl.py, tests/unit/test_infos.py
The control protocol client allows a user scriptlet to execute the
default handler for a step in the running application context, or set
the value of a custom variable previously passed as an argument to
`LifecycleManager`.
The `craft_parts.ctl` module can be imported by application-defined
clients, or invoked as a utility from the command line using the
supplied `partsctl` tool.
-----
=> ctl: add ctl protocol client (CRAFT-35)

craft_parts/executor/step_handler.py, craft_parts/packages/__init__.py, craft_parts/packages/deb.py, craft_parts/packages/normalize.py, tests/unit/packages/test_normalize.py
Packages unpacked in the stage area may contain files that need to be
patched to work correctly. Patches include replacing absolute pathnames
to the python interpreter in script shebangs, converting absolute
symlinks to relative, cleaning suid/guid bits, and changing path names
in pkg-config and xml2/xslt config files to reflect the new installation
root.
The implementation of package normalization and tests is ported from
Snapcraft, and will be replaced by an upcoming stand-alone package
containing repository and package operations.
-----
=> packages: normalize unpacked stage packages (CRAFT-33)

craft_parts/packages/apt_cache.py, craft_parts/packages/errors.py, tests/unit/packages/test_apt_cache.py, tests/unit/packages/test_errors.py
A port of the snapcraft PR #3528 by Chris Patterson. Original
description follows:
* Add some checks to ensure package.candidate is not None before using
it. If it is None, when expected to not be `None`, raise a
`PackageNotFoundError` with the name of the package in question.
* Do not iterate over all packages when unmarking. This is the cause of
https://forum.snapcraft.io/t/snapcraft-crash-when-esm-repositories-are-present/24587/8
where a package was being inspected that did not have an available candidate,
causing Snapcraft to fail unnecessarily.
Co-authored-by: Chris Patterson <chris.patterson@canonical.com>
-----
=> packages: handle packages with no candidate (CRAFT-219)

craft_parts/callbacks.py, craft_parts/executor/part_handler.py, tests/integration/executor/test_callbacks.py, tests/unit/executor/test_executor.py, tests/unit/test_callbacks.py
Add integraton tests for callbacks, renaming `callbacks.clear()` to
`callbacks.unregister_all()` to be consistent with the unregister method
used for plugins.
-----
=> callbacks: add integration tests (CRAFT-223)

requirements-dev.txt, tests/unit/packages/test_deb.py
When unpacking stage packages, it's not necessary to normalize unpacked
files if nothing was unpacked. This test verifies if no such call is
made in this case.
This is a follow-up to PR #76, and adds the normalization call test included in
https://github.com/snapcore/snapcraft/pull/3534.
-----
=> packages: add test to ensure unnecessary normalize not called (CRAFT-221)

craft_parts/packages/snaps.py, tests/fake_snapd.py, tests/unit/state_manager/test_state_manager.py, tests/unit/test_sequencer.py
Pyright 1.1.151 warns about many instances of None indexing that were
ignored by previous versions, address them.
-----
=> packages: address issues raised by pyright 1.1.151 (CRAFT-303)

craft_parts/state_manager/reports.py, tests/integration/lifecycle/test_lifecycle.py, tests/unit/state_manager/test_reports.py, tests/unit/state_manager/test_state_manager.py
Clarify the message to include the dependency step name in the reason
why the step is being re-executed.
-----
=> sequencer: improve dirty state report message (CRAFT-302)

craft_parts/__main__.py, craft_parts/lifecycle_manager.py, craft_parts/main.py, craft_parts/packages/deb.py, tests/integration/test_main.py
Provide a basic tool to execute part building according to a yaml
file containing a parts-based project. This can be executed from the
command line with `python3 -mcraft_parts -f <yaml_file>` (`parts.yaml`
is assumed if no file is specified).
-----
=> cli: add a main entry point (CRAFT-34)

craft_parts/state_manager/states.py, setup.py, tests/unit/sources/test_base.py, tox.ini
Make craft-parts compatible with Python 3.7. Also fix tests to accept
error messages that changed in Python 3.9, and update tox configuration.
-----
=> platform: compatibility fixes for python 3.7 and 3.9 (CRAFT-315)

craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/lifecycle_manager.py, craft_parts/packages/apt_cache.py, craft_parts/packages/deb.py, craft_parts/packages/snaps.py, craft_parts/utils/os_utils.py, craft_parts/utils/url_utils.py, tests/integration/plugins/test_application_plugin.py, tests/unit/executor/test_step_handler.py, tests/unit/packages/test_apt_cache.py, tests/unit/packages/test_deb.py
Craft-parts shouldn't pollute the application output with its own
messages. This is an interim solution, send the output to the log
until the user message handling library is available.
Output example ("Execute" messages are printed by the cli utility):
```
$ python3 -mcraft_parts -fparts-mpg123.yaml 
WARNING:craft_parts.packages.apt_cache:libasound-dev is a virtual package, use non-virtual packages for deterministic results.
Execute: Pull mpg123
Execute: Build mpg123
Execute: Stage mpg123
Execute: Prime mpg123
```
-----
=> many: send craft-parts output to logger (CRAFT-365)

craft_parts/parts.py, tests/unit/test_parts.py
Validate stage and prime to detect absolute paths on unmarshal, instead
of doing it at execution time when the filter is used.
-----
=> parts: add validators for stage and prime filesets (CRAFT-366)

craft_parts/dirs.py, craft_parts/executor/executor.py, craft_parts/executor/part_handler.py, craft_parts/infos.py, craft_parts/lifecycle_manager.py, craft_parts/sequencer.py, craft_parts/sources/base.py, craft_parts/sources/local_source.py, craft_parts/sources/sources.py, craft_parts/sources/tar_source.py, craft_parts/state_manager/state_manager.py, pyproject.toml, tests/unit/sources/test_local_source.py, tests/unit/state_manager/test_state_manager.py, tests/unit/test_dirs.py, tests/unit/test_infos.py, tests/unit/test_lifecycle_manager.py
Work directories and files generated by the application in the current
directory (which may be a local source for plugins) should be ignored when
pulling sources. This change fixes a number of issues related to file
patterns to ignore:
- Don't pull local sources matching the patterns to ignore, otherwise the
newly generated application file may be also considered a source file.
- Allow the application to configure ignore patterns to match files it
generated (such as `*.snap` for snapcraft, or `*.charm` for charmcraft).
- When a work directory is set, ignore it instead of the standard parts,
prime, stage directories.
-----
=> many: fix source ignore patterns (CRAFT-375)

craft_parts/utils/os_utils.py
This fixes the uname call in MacOS. Problem found during charmcraft tests.
-----
=> utils: provide uname call with non-gnu options (CRAFT-382)

craft_parts/lifecycle_manager.py, craft_parts/packages/apt_cache.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, craft_parts/utils/os_utils.py, pyproject.toml, tests/unit/packages/test_apt_cache.py, tests/unit/packages/test_base.py, tests/unit/utils/test_os_utils.py
Snap environment detection returned false positives and was not being
properly tested. Fix snap environment detection and add tests for
`is_snap()` and `is_inside_container()`.
-----
=> utils: fix snap environment detection and add tests (CRAFT-376)

craft_parts/packages/deb.py, craft_parts/packages/snaps.py, tests/unit/packages/test_deb.py, tests/unit/packages/test_snaps.py
Remove sudo calls from apt and snap install calls, and fail instead
if permission to run is insufficient. Sudo is not necessary in the
provider environment because the application already runs as root.
-----
=> packages: remove sudo calls (CRAFT-384)

craft_parts/lifecycle_manager.py, craft_parts/plugins/__init__.py, craft_parts/plugins/plugins.py, tests/integration/plugins/test_application_plugin.py, tests/unit/plugins/test_plugins.py
Stripping plugin properties shouldn't change original parts data that
has been supplied by the application using craft-parts.
-----
=> plugins: strip plugin properties in non-destructive way (CRAFT-394)

craft_parts/errors.py, tests/integration/plugins/test_application_plugin.py, tests/unit/test_errors.py, tests/unit/test_parts.py
Change formatting of pydantic errors to be more human-readable. The
new format is similar to the one used in Charmcraft. Specifically,
this changes
```
'foo',1: some error happened
'bar': field required
'baz': extra fields not permitted
```
to
```
- some error happened in field 'foo[1]'
- field 'bar' is required'
- extra field 'baz' not permitted
```
Co-authored-by: Chris Patterson <chris.patterson@canonical.com>
-----
=> errors: reformat pydantic validation error (CRAFT-368)

tests/integration/sources/test_tar.py
Make sure we can correctly read a valid tar source.
-----
=> tests: add tar source integration test (CRAFT-197)

craft_parts/sources/local_source.py, tests/unit/executor/test_part_handler.py, tests/unit/sources/test_local_source.py
When verifying if a pulled source is outdated, also check for files
or directories that might have been deleted from the source directory.
If this is the case, also remove the files or directories from the
part source directory.
-----
=> sources: verify deleted files in outdated check (CRAFT-440)

craft_parts/executor/part_handler.py, tests/unit/executor/test_part_handler.py
Rerunning a part step should invalidate not only its state but also
the state of subsequent steps in the same part. This is correctly
implemented in action planning but not in execution. Fix the action
executor to clean all the necessary steps and not only the step being
re-executed.
-----
=> executor: fix rerun action to clean subsequent steps (CRAFT-441)

craft_parts/__init__.py
Once applications want to catch this exception, it should probably be exposed from the package rather than require reference to the module.
Signed-off-by: Chris Patterson <chris.patterson@canonical.com>
-----
=> craft_parts: export PartsError in base package (CRAFT-456)

Makefile, setup.py
Prevent autoformatting in venvs, etc. and ensure all sources
are consistently covered with formatter/linter targets.
Define SOURCES and use for the relevant target commands.
Signed-off-by: Chris Patterson <chris.patterson@canonical.com>
-----
=> Makefile: define sources for formatting/linting

craft_parts/utils/os_utils.py, tests/unit/utils/test_os_utils.py
Add utilities to mount and unmount filesystems. These are thin wrappers
around the system mount and umount commands.
-----
=> utils: add filesystem mounting calls (CRAFT-460)

setup.py
Linters now run on setup.py. Address issues so that `make lint` and
`make tests` execute as expected.
-----
=> packaging: address linter issues in setup.py (CRAFT-461)

craft_parts/overlays/__init__.py, craft_parts/overlays/errors.py, craft_parts/overlays/overlay_fs.py, tests/unit/overlays/test_errors.py, tests/unit/overlays/test_overlay_fs.py
Add helpers to mount and unmount overlayfs filesystems, and to
identify special files and directories used in filesystem layering.
-----
=> overlay: add overlayfs helpers (CRAFT-462)

craft_parts/dirs.py, craft_parts/parts.py, craft_parts/sequencer.py, craft_parts/state_manager/state_manager.py, tests/unit/test_dirs.py, tests/unit/test_parts.py
Define the overlay work directory. Add part properties to retrieve
overlay-related subdirectories and identify if a part has overlay
parameters or overlay visibility.
-----
=> overlay: add overlay support to parts (CRAFT-470)

craft_parts/overlays/__init__.py, craft_parts/overlays/overlays.py, tests/unit/overlays/test_overlays.py
Add helper functions to obtain the sets of migratable files and
directories from each overlay layer considering whited out entries and
opaque directories.
-----
=> overlay: add layer visibility helpers (CRAFT-477)

craft_parts/sources/base.py, tests/unit/sources/test_local_source.py
Source handlers may modify the list of ignore patterns, so make a new
copy for each source handler instance.
-----
=> sources: copy mutable ignore pattern for source handlers (CRAFT-494)

craft_parts/lifecycle_manager.py, craft_parts/packages/apt_cache.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, tests/integration/lifecycle/test_lifecycle.py, tests/integration/test_main.py, tests/unit/packages/test_apt_cache.py, tests/unit/packages/test_base.py
Instead of having a split state for stage cache, rely on the
host's cache by setting the state directory to /var/lib/apt.
With this, we can remove the update() interface which is no
longer required.
This effectively causes the refresh_stage_packages_list()
to noop.
Signed-off-by: Chris Patterson <chris.patterson@canonical.com>
-----
=> packages/apt: use host state for apt cache (CRAFT-487)

craft_parts/overlays/__init__.py, craft_parts/overlays/layers.py, craft_parts/sequencer.py, tests/unit/overlays/test_layers.py
The sequencer must keep track of layer state and changes in order to
emit actions related to the overlay step (such as layer reapplications
or re-execution of steps invalidated by changes in layers). Add a
layer state management helper to be used during the planning phase
to store the layer hash corresponding to each part and compute the
expected values to ensure overlay consistency.
-----
=> overlay: add layer state management helper (CRAFT-506)

craft_parts/executor/migration.py, craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/overlays/__init__.py, craft_parts/overlays/overlays.py, craft_parts/parts.py, craft_parts/state_manager/__init__.py, tests/unit/executor/test_migration.py, tests/unit/executor/test_part_handler.py, tests/unit/test_parts.py
Migrate overlay tree entries to stage and prime areas, handling
whiteouts and translating overlayfs whiteout files and opaque
directories to OCI. Cleanup of overlay files in shared areas is
done when the last part with overlay parameters is cleaned.
Note: collision detection in overlay staging will be implemented
in a forthcoming PR.
-----
=> overlay: migrate overlay data to stage and prime (CRAFT-468, CRAFT-82)

craft_parts/main.py
The parts specification error when running craft-parts from the CLI
tool entry point lacks information, add details on what cause the
reported error.
With this fix, parts errors will look like:
```
$  python -mcraft_parts
Error: invalid parts specification: Part 'p1' validation failed.                                                                                                                                
'source' is required by the dump plugin                                                         
Review part 'p1' and make sure it's correct.
```
-----
=> main: add details to the parts specification error message (CRAFT-512)

craft_parts/executor/executor.py, craft_parts/lifecycle_manager.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, craft_parts/packages/errors.py, tests/integration/plugins/test_application_plugin.py, tests/unit/executor/test_executor.py, tests/unit/packages/test_base.py, tests/unit/packages/test_deb.py, tests/unit/packages/test_errors.py
Add a helper to download packages from a repository to a cache area
so that they can be installed later on the overlay step chroot.
-----
=> packages: add package download helper (CRAFT-511)

craft_parts/main.py
Future craft tools will adopt `--trace` as the standard CLI option to
display debug messages, and Snapcraft uses `--debug` for a different
purpose. Rename the craft-parts CLI option to be consistent with tools.
-----
=> main: rename debug option to trace for consistency (CRAFT-513)

craft_parts/packages/apt_cache.py, tests/unit/packages/test_apt_cache.py
Pyright warns that `apt_pkg` is not exported from module `apt`. Use
the toplevel `apt_pkg` module directly instead.
-----
=> packages: fix apt_pkg imports (CRAFT-534)

tests/integration/sources/test_tar.py
The tar source integration test incorrectly stated its license as GPL,
update with the LGPL license notice.
-----
=> licensing: fix license notice in tar source test (CRAFT-533)

craft_parts/errors.py, craft_parts/executor/executor.py, craft_parts/executor/part_handler.py, craft_parts/state_manager/overlay_state.py, craft_parts/state_manager/states.py, tests/integration/sequencer/test_sequencer.py, tests/unit/executor/test_migration.py, tests/unit/executor/test_part_handler.py, tests/unit/test_errors.py
The overlay step execution handler mounts the overlay stack to install
packages and execute user scripts.  During the build step, parts with
overlay visibility should be able to see the overlay filesystem mounted.
-----
=> executor: add overlay step handling (CRAFT-86)

craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/lifecycle_manager.py, craft_parts/main.py, craft_parts/parts.py, craft_parts/sequencer.py, craft_parts/state_manager/states.py, craft_parts/steps.py, tests/integration/executor/test_callbacks.py, tests/integration/lifecycle/test_lifecycle.py, tests/integration/lifecycle/test_partsctl.py, tests/integration/lifecycle/test_stage_snaps.py, tests/integration/plugins/test_application_plugin.py, tests/integration/sequencer/test_sequencer.py, tests/integration/test_main.py, tests/unit/executor/test_part_handler.py, tests/unit/executor/test_step_handler.py, tests/unit/state_manager/test_state_manager.py, tests/unit/test_lifecycle_manager.py, tests/unit/test_parts.py, tests/unit/test_sequencer.py, tests/unit/test_steps.py
The overlay step is used to process filesystem mutations defined for
each part. It can include package installation, modification of existing
file data or metadata, file renaming or removal, etc.
**Note to reviewers:** this change is rather large because many subsystems
need to be updated to handle the new step, and tests need to be updated to
account for the actions corresponding to step changes. Additional integration
tests will be added after the outdated overlay verification tests land, covering
the usage scenarios described in the feature specification.
=> many: add overlay step (CRAFT-84)

.github/workflows/tests.yaml, craft_parts/executor/part_handler.py, craft_parts/overlays/chroot.py, craft_parts/overlays/overlay_fs.py, craft_parts/overlays/overlay_manager.py, craft_parts/utils/os_utils.py, requirements-dev.txt, requirements.txt, setup.py, tests/unit/overlays/test_chroot.py, tests/unit/overlays/test_overlay_manager.py, tests/unit/utils/test_os_utils.py
Add a simple, non-magic replacement for pychroot. Pychroot has numerous
issues such as being too hackish, being restricted to certain interpreter
versions and platforms, and not working in the CI environment. This
implementation is much simpler and we can actually understand it.
-----
=> overlays: replace pychroot with non-magic chroot (CRAFT-558)

.bumpversion.cfg, craft_parts/__init__.py, craft_parts/executor/environment.py, craft_parts/executor/step_handler.py, craft_parts/packages/deb.py, craft_parts/packages/errors.py, craft_parts/plugins/__init__.py, docs/changelog.rst, docs/conf.py, setup.py, tests/unit/executor/test_environment.py, tests/unit/packages/test_deb.py, tests/unit/packages/test_errors.py
Changelog
========
* Properly declare public API names
* Allow non-snap applications running on non-apt systems to invoke parts processing on build providers
* Use Bash as script interpreter instead of /bin/sh to stay compatible with Snapcraft V2 plugins
-----
=> release: craft-parts 1.0.3 (CRAFT-576)

craft_parts/errors.py, craft_parts/lifecycle_manager.py, tests/integration/executor/test_callbacks.py, tests/integration/lifecycle/test_overlay.py, tests/integration/lifecycle/test_partsctl.py, tests/unit/test_errors.py, tests/unit/test_lifecycle_manager.py
The overlay step is only supported on Linux and must be executed as
the superuser. Add a verification to lifecycle manager creation to
make sure these prerequisites are satisfied if the project uses
overlay.
-----
=> lifecycle_manager: check if overlay is supported (CRAFT-562)

craft_parts/sources/base.py, craft_parts/sources/errors.py, craft_parts/sources/git_source.py, craft_parts/sources/sources.py, tests/unit/sources/test_errors.py, tests/unit/sources/test_git_source.py
The git source handler allows specifying git repositories as a part
source. Code and tests ported from snapcraft, with repository
initialization and write methods removed.
-----
=> sources: add the git source handler (CRAFT-588)

.github/workflows/tests.yaml, .readthedocs.yml, Makefile, docs/conf.py, docs/requirements.txt, pyproject.toml, requirements-bionic.txt, requirements-focal.txt, setup.py
- Remove requirements to always test with the latest
- Separate the docs target into its own requirements for readthedocs
- Ensure the right dependencies are used to create the documentation
assets
- Remove black's file filter which ignores gitignore
- Use 20.04 as the only base with a spread of python versions
- Ensure the sudo context of the GHA for overlays runs the correct
python interpreter
-------
-----
=> python: unpin dependencies (CRAFT-663)

craft_parts/errors.py, craft_parts/executor/environment.py, craft_parts/executor/executor.py, craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/plugins/__init__.py, craft_parts/plugins/base.py, craft_parts/plugins/validator.py, tests/integration/plugins/test_validate_environment.py, tests/unit/executor/test_environment.py, tests/unit/executor/test_step_handler.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_validator.py, tests/unit/test_errors.py
Plugins may require certain environment elements to be present in
order to build a part, regardless of how these elements were installed
on the system. For example, a compiler may have been installed from a
deb package, a snap, built from sources or even built by a different
part. This commit adds plugin environment validators, allowing plugins
to verify if the system environment is correct before building a part.
**Note to reviewers**: see the integration test for use cases.
-----
=> plugins: add plugin environment validation (CRAFT-611)

.github/workflows/tests.yaml, craft_parts/plugins/go_plugin.py, craft_parts/plugins/plugins.py, craft_parts/plugins/validator.py, tests/integration/plugins/test_go.py, tests/integration/plugins/test_validate_environment.py, tests/unit/plugins/test_go_plugin.py
Add a plugin for go projects using go.mod.  Plugin build definitions
are based on the Snapcraft V2 go plugin.
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
=> plugins: add go plugin (CRAFT-48)

setup.py
Pin dependencies with API changes to allow craft-parts to run correctly.
Code will be updated to the current API in a separate PR. Pylint will
be unpinned after warnings issued by newer versions are addressed.
Fixes #158.
-----
=> setup: pin pydantic-yaml and pydantic versions (CRAFT-718)

craft_parts/packages/snaps.py
This is a port of snapcore/snapcraft#3617 to craft-parts.
-----
=> snap: do not refresh already installed snaps

craft_parts/errors.py, setup.py, tests/unit/executor/test_part_handler.py, tests/unit/state_manager/test_step_state.py, tests/unit/test_errors.py, tests/unit/test_sequencer.py
Pydantic 1.9 uses `TypedDict` to hold validation error information
instead of a plain dictionary. Update craft-parts to correctly
handle `ErrorDict` data.
-----
=> errors: update pydantic validation error checking (CRAFT-788)

craft_parts/executor/part_handler.py, tests/unit/executor/test_part_handler.py
When obtaining the consolidated list of build packages, honor the
source type specified by the user before attempting to infer it
from the source URI. Fixes #171.
-----
=> executor: use source type specified in part (CRAFT-831)

tests/unit/sources/test_git_source.py
Signed-off-by: Callahan Kovacs <callahan.kovacs@canonical.com>
-----
=> lint: missing f-string prefix

.github/workflows/tests.yaml, craft_parts/overlays/overlay_fs.py, craft_parts/utils/os_utils.py, tests/integration/executor/test_callbacks.py, tests/integration/lifecycle/test_partsctl.py, tests/unit/executor/test_part_handler.py, tests/unit/overlays/test_overlay_fs.py, tests/unit/overlays/test_overlay_manager.py, tests/unit/utils/test_os_utils.py
Use fuse-overlayfs instead of the kernel implementation to enable
mounting inside idmapped containers in focal with updated kernels.
-----
=> overlays: mount overlayfs using fuse-overlayfs

craft_parts/executor/executor.py, craft_parts/infos.py, tests/integration/lifecycle/test_craftctl.py, tests/unit/test_infos.py
Don't check the write-once flag when updating project vars from
skipped actions because we may have multiple skipped steps after
the variable is set.
-----
CRAFT-942
=> infos: use raw write to set project vars from actions

craft_parts/executor/executor.py, craft_parts/infos.py, craft_parts/lifecycle_manager.py, tests/integration/lifecycle/test_craftctl.py, tests/unit/test_infos.py
Restrict variable setting to the part specified when creating the
parts lifecycle. Applications that don't declare project variables
don't need to specify an adopting part.
-----
CRAFT-963
=> craftctl: set variables from parts adopting metadata

craft_parts/state_manager/state_manager.py, tests/unit/state_manager/test_state_manager.py
Verification of dirty parts can take more time than expected when
a project has a large number of dependency-chained parts (this
happens with gnome-sdk). Cache reports to cut recursion earlier.
-----
CRAFT-974
=> state_manager: cache dirty reports to reduce recursion

craft_parts/lifecycle_manager.py
=> docs: fix typo in lifecycle manager docstrings

craft_parts/lifecycle_manager.py, tests/unit/test_lifecycle_manager.py
Argument `extra_build_snaps` is used to specify additional snaps
to be installed on the build instance.
-----
=> lifecyle_manager: add missing extra build snaps argument

tests/unit/test_infos.py
Make sure `project_name` can be retrieved from `project_info`,
`part_info` and `step_info`.
-----
=> tests: add project name info tests

craft_parts/executor/part_handler.py, craft_parts/sources/base.py, craft_parts/sources/git_source.py, craft_parts/sources/local_source.py, craft_parts/sources/snap_source.py, craft_parts/sources/tar_source.py, setup.py, tests/unit/executor/test_part_handler.py, tests/unit/sources/test_base.py, tests/unit/sources/test_snap_source.py, tests/unit/sources/test_tar_source.py
Target cleaning was used in snapcraft only for plugins v1 and is not
used in craft_parts, so remove the option to simplify source handlers.
Existing target cleaning implementation was also flawed, see
https://github.com/python/cpython/issues/73759.
-----
=> sources: remove provisioning option to clean target

craft_parts/sources/sources.py, craft_parts/sources/tar_source.py, craft_parts/sources/zip_source.py, tests/integration/sources/test_zip.py, tests/unit/sources/test_tar_source.py, tests/unit/sources/test_zip_source.py
Allow parts to specify zip files as sources.
Co-authored-by: Kyle Fazzari <kyle@canonical.com>
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
Co-authored-by: Marius Gripsgard <marius@ubports.com>
-----
=> sources: add zip file source handler

craft_parts/infos.py, tests/unit/test_infos.py
Allow setting variable regardless of adopting part when in raw mode.
-----
=> infos: fix project var raw write

craft_parts/packages/normalize.py, tests/unit/packages/test_normalize.py
Use `os.path.relpath()` instead of `Path.relative_to()` to normalize
symlinks requiring parent path components.
-----
=> packages: fix symlink normalization

.readthedocs.yml, docs/index.rst, docs/requirements.txt, setup.py
Install missing packages in readthedocs environment and add changelog
to the documentation index.
Removing python-apt from setup packages was also required because the
version of python-apt in PyPI is outdated and readthedocs tries to
install it over the existing version previously installed from sources.
This shouldn't be a problem because applications are also required to
install python-apt.
-----
=> docs: fix readthedocs documentation generation

craft_parts/executor/executor.py, craft_parts/executor/part_handler.py, craft_parts/plugins/validator.py, setup.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_dotnet_plugin.py, tests/unit/plugins/test_go_plugin.py, tests/unit/plugins/test_meson_plugin.py, tests/unit/plugins/test_npm_plugin.py, tests/unit/plugins/test_rust_plugin.py, tests/unit/plugins/test_validator.py
Plugin environment validators may need to use plugin options values,
add that to the validator instance.
-----
=> plugins: make plugin options available in validator

craft_parts/executor/environment.py, craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/infos.py, tests/integration/executor/test_environment.py, tests/unit/executor/test_environment.py, tests/unit/test_infos.py
Allow application-defined variables to be used during step scriptlet
execution. Applications can use the pre-step callback to set step
environment variables or the prologue callback to set global environment
variables.
-----
CRAFT-1070
=> executor: enable application-defined environment variables

craft_parts/callbacks.py, craft_parts/executor/executor.py, craft_parts/infos.py, tests/integration/executor/test_callbacks.py, tests/integration/executor/test_environment.py, tests/unit/executor/test_executor.py, tests/unit/test_callbacks.py
Be more conservative on what we expose to the application in the
prologue/epilogue callbacks. Pass only project info for now,
and add more later if needed.
Also remove unnecessary method definition from step information.
-----
=> callbacks: don't pass part list to prologue callback

craft_parts/__init__.py, craft_parts/executor/__init__.py, craft_parts/executor/environment.py, craft_parts/lifecycle_manager.py, tests/integration/executor/test_environment.py, tests/unit/executor/test_environment.py, tests/unit/executor/test_replace_attr.py
Replace global environment variables used in parts values.
Co-authored-by: Kyle Fazzari <kyrofa@ubuntu.com>
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
CRAFT-1073
=> environment: expand global variables

craft_parts/plugins/dotnet_plugin.py, craft_parts/plugins/go_plugin.py, craft_parts/plugins/meson_plugin.py, craft_parts/plugins/npm_plugin.py, craft_parts/plugins/rust_plugin.py, craft_parts/plugins/validator.py, tests/unit/plugins/test_dotnet_plugin.py, tests/unit/plugins/test_go_plugin.py, tests/unit/plugins/test_meson_plugin.py, tests/unit/plugins/test_npm_plugin.py, tests/unit/plugins/test_rust_plugin.py
Setup plugin validation so it only mentions a dependency on one
part. This is still not the best solution to the problem.
Also fixup the node verification for it to check if node is to be
included and if so, skip verification.
-----
I am not entirely happy with this solution. Proposing for discussion.
=> plugin: plugin validation with only one part dep

craft_parts/packages/snaps.py, tests/fake_snap_command.py
Snap installation leaks stdout output that conflicts with craft-cli
when executing the lifecycle from an application. Run subprocesses
silently to avoid this problem.
Fixes #218
-----
=> packages: run snap operations silently

craft_parts/sources/git_source.py, tests/unit/executor/test_collisions.py, tests/unit/sources/test_git_source.py
-----
Resolving two problems:
Unit tests fail on systems with the git config option `init.defaultbranch`.
Setting the global config `init.defaultbranch=main` is becoming more common on developer systems for inclusivity. 
When `source_branch` is defined, `pull_existing()` function wasn't pulling the latest changes.  
I wrote regression tests and updated the `git reset --hard <refspec>` call.
=> source: git: handle git init.defaultbranch and pull existing from remote

.bumpversion.cfg, craft_parts/__init__.py, craft_parts/executor/part_handler.py, craft_parts/lifecycle_manager.py, craft_parts/parts.py, craft_parts/sources/git_source.py, docs/changelog.rst, docs/conf.py, pyproject.toml, setup.py, tests/unit/executor/test_collisions.py, tests/unit/executor/test_part_handler.py, tests/unit/sources/test_git_source.py
* Fix git repository updates
* Fix stage packages removal on build update
-----
=> Release 1.7.2

craft_parts/executor/part_handler.py, craft_parts/lifecycle_manager.py, craft_parts/main.py, tests/integration/executor/test_environment.py, tests/integration/executor/test_steps.py, tests/integration/lifecycle/test_lifecycle.py, tests/integration/plugins/conftest.py, tests/unit/executor/test_part_handler.py, tests/unit/test_lifecycle_manager.py
Add the list of primed stage packages to the prime state, and make
the list of pull assets and primed stage packages available from the
lifecycle manager.
-----
CRAFT-1174
=> executor: store primed stage packages in prime state

craft_parts/executor/part_handler.py, tests/unit/executor/test_part_handler.py
Empty scriptlets should be handled as such and not as undefined
scriptlets. In the former case, the built-in handler for the step
is not executed, the empty scriptlet is executed instead.
-----
CRAFT-1182
=> executor: handle empty scriptlets

craft_parts/executor/filesets.py, tests/unit/executor/test_filesets.py
The scenario where the stage filter is unspecified and the prime file
excludes all files must not fail with a wildcard symbol conflict.
-----
CRAFT-1188
=> filters: prevent wildcard symbol conflict

Makefile, craft_parts/executor/executor.py, craft_parts/parts.py, craft_parts/plugins/plugins.py, tests/unit/test_lifecycle_manager.py
-----
Change `plugin` to `plugin_name`, because it is a string, not a `Plugin` object.
I would like to land this prior to https://github.com/canonical/craft-parts/pull/250#pullrequestreview-1042330556.
=> fix: rename plugin to plugin_name

craft_parts/executor/part_handler.py, craft_parts/parts.py, craft_parts/plugins/base.py, craft_parts/plugins/cmake_plugin.py, craft_parts/plugins/meson_plugin.py, tests/integration/plugins/test_cmake.py, tests/integration/plugins/test_meson.py, tests/unit/executor/test_part_handler.py, tests/unit/plugins/test_autotools_plugin.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_cmake_plugin.py, tests/unit/plugins/test_dotnet_plugin.py, tests/unit/plugins/test_dump_plugin.py, tests/unit/plugins/test_go_plugin.py, tests/unit/plugins/test_make_plugin.py, tests/unit/plugins/test_meson_plugin.py, tests/unit/plugins/test_nil_plugin.py, tests/unit/plugins/test_npm_plugin.py, tests/unit/plugins/test_plugins.py, tests/unit/plugins/test_python_plugin.py, tests/unit/plugins/test_rust_plugin.py, tests/unit/test_parts.py
-----
Plugins that supported out-of-source building were not working with the source-subdir parameter.
There were two minor issues:
1. A missing check for out-of-source plugins when determining the build directory
2. `cmake` and `meson` plugins not choosing the right source directory
Unfortunately, accessing the out_of_source_build property prior to instantiating the plugin was a challenge. I've made some comments below.
(CRAFT-1185)
=> parts: check for out of source builds

craft_parts/executor/step_handler.py, craft_parts/packages/normalize.py, tests/unit/packages/test_normalize.py
-----
When normalizing pkg-config (.pc) files from staged snaps, directories previously prepended to the prefix parameter will be removed:
- `/build/<snap-name>/stage` from snaps built via launchpad
-  `/root/stage` from snaps built via a provider
An almost duplicate of https://github.com/snapcore/snapcraft/pull/3848.
LP: #[1916281](https://bugs.launchpad.net/snapcraft/+bug/1916281)
(CRAFT-1215)
=> repo: fix_pkg_config removes prefixes from staged snap's .pc files.

craft_parts/utils/file_utils.py
-----
Latest Pyright release fixed a bug and found a new error!
Pyright 1.1.264 [changelog](https://github.com/microsoft/pyright/releases/tag/1.1.264):
`Bug Fix: Fixed a bug that resulted in incorrect type inference for unannotated parameters with a default argument value in an __init__ method.`
Source: https://github.com/canonical/craft-parts/blob/7c8140f4c69959674afee30109a36cc8697bb873/craft_parts/sources/local_source.py#L41
Error: 
```
pyright 1.1.264
/home/developer/dev/craft-parts/craft_parts/executor/part_handler.py
/home/developer/dev/craft-parts/craft_parts/executor/part_handler.py:601:31 - error: Argument of type "(source: str, destination: str, *, follow_symlinks: bool = False) -> None" cannot be assigned to parameter "copy_function" of type "(source: str, destination: str, …
```
=> lint: normalize link(), copy(), and link_or_copy() signatures

craft_parts/packages/normalize.py, tests/unit/packages/test_normalize.py
-----
Follow up to https://github.com/canonical/craft-parts/pull/251 thanks to an idea from @cmatsuoka.
When normalizing pkg-config (.pc) files from staged snaps, the previously prepended `<path-to-project-path>/stage` will be removed from the `prefix` parameter.
This means all directories prior to and including `stage/` are trimmed.
For example, `/root/stage/usr` is trimmed to `/usr`.
LP: #[1916281](https://bugs.launchpad.net/snapcraft/+bug/1916281)
(CRAFT-1215)
=> repo: fix_pkg_config trims prefixes more generically

craft_parts/packages/normalize.py, tests/unit/packages/test_normalize.py
-----
This reverts commit f6681f0fef39c38c1a4d3a7808d9e66cb884a369.
This commit caused craft-part's behavior to change when `stage` is part of the pwd.
=> Revert "repo: fix_pkg_config trims prefixes more generically"

.bumpversion.cfg, craft_parts/__init__.py, craft_parts/packages/normalize.py, docs/changelog.rst, docs/conf.py, setup.py, tests/unit/packages/test_normalize.py
* Change staged snap pkgconfig prefix normalization to be predictable  regardless of the path used for destructive mode packing
-----
=> Release 1.10.1

craft_parts/executor/part_handler.py, craft_parts/infos.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, tests/unit/executor/test_part_handler.py, tests/unit/packages/test_deb.py
-----
`stage-packages` are now fetched from the host architecture's repositories instead of the target architecture's repository.
This was causing an error during cross-compiling because the target architecture's repository was not registered.
LP: #[1983009](https://bugs.launchpad.net/snapcraft/+bug/1983009)
(CRAFT-1216)
=> packages: fetch stage-packages from host arch's repo

craft_parts/utils/os_utils.py, tests/unit/utils/test_os_utils.py
Update `get_bin_paths()`, `get_include_paths()`, `get_library_paths()`
to use pathlib.
-----
=> utils: refactor os utils to use pathlib

craft_parts/plugins/cmake_plugin.py, tests/integration/plugins/test_cmake.py, tests/unit/plugins/test_cmake_plugin.py
Properly format the cmake prefix path string, and set the installation
prefix to match v1 plugins.
-----
CRAFT-1154
=> plugins: fix cmake plugin prefix

craft_parts/plugins/cmake_plugin.py, tests/integration/plugins/test_cmake.py, tests/unit/plugins/test_cmake_plugin.py
Setting `CMAKE_INSTALL_PREFIX` by default makes the cmake plugin
compatible with the Snapcraft cmake plugin for core18 and solves
usability issues, but it also breaks compatibility with existing
core22 snaps that expect binaries to be installed in `usr/local/bin`
by default.
To keep compatibility with existing core22 snaps, the prefix path
will not be defined by default, and snap authors are encouraged
to define `-DCMAKE_INSTALL_PREFIX=` in cmake parameters to be
compatible with the core18 cmake plugin, so that libraries
built with cmake and staged by a different part can be correctly
detected without the need to define additional parameters such as
`CMAKE_INCLUDE_PATH` and `CMAKE_LIBRARY_PATH`.
-----
=> plugins: drop cmake install prefix argument

craft_parts/sources/base.py, tests/unit/utils/test_url_utils.py
pylint 2.15 adds a new warning on timeout-less calls to
`requests.get()`, as it's a potentially endless call. The value of 10
seconds is arbitrary and can change if needed.
-----
=> lint: set a timeout in `requests.get()`

craft_parts/errors.py, craft_parts/packages/deb.py, craft_parts/sources/deb_source.py, craft_parts/sources/sources.py, craft_parts/utils/deb_utils.py, tests/integration/sources/test_deb.py, tests/unit/sources/test_deb_source.py
Unpack deb packages in the same way that the stage-packages DebPackage
does (via dpkg-deb). This motivates a small refactoring to move
"extract_deb()" to a place that both handlers can use.
A lot of the code on this PR comes from a work-in-progress branch by @cmatsuoka . Thanks!
-----
CRAFT-117
=> sources: support "deb" sources

craft_parts/plugins/go_plugin.py, tests/integration/plugins/test_go.py, tests/integration/plugins/test_go/gen/generator.go, tests/integration/plugins/test_go/go.mod, tests/unit/plugins/test_go_plugin.py
plugins: support "go generate" in go parts
GoPlugin's build step will now call "go generate" before the actual
build/install to support code generation. This shouldn't affect existing
uses of the plugin because the call is harmless if there's no code to
generate.
-----
CRAFT-1316
=> plugins: support "go generate" in go parts

craft_parts/executor/migration.py, craft_parts/executor/part_handler.py, craft_parts/main.py, craft_parts/overlays/__init__.py, craft_parts/overlays/overlay_manager.py, craft_parts/overlays/overlays.py, tests/unit/executor/test_migration.py, tests/unit/executor/test_part_handler.py, tests/unit/overlays/test_overlays.py
Remove whiteout files (or opaque directory markers) from the prime
directory if they don't have a corresponding entry in the base layer
to be whited out.
-----
CRAFT-1264
=> migration: filter out unnecessary whiteout files

craft_parts/__init__.py, craft_parts/parts.py, tests/unit/test_parts.py
Add a part validation helper that validates part data against the part and plugin models. Currently all craft tools validate part data, so do it in the library instead of implementing a validator in each application.
Fixes #176.
-----
=> parts: add part validator

craft_parts/executor/filesets.py, tests/integration/lifecycle/test_filters.py, tests/unit/executor/test_filesets.py
Filter combination was computed with filters reversed, resulting in unexpected behavior when both stage and prime filters are defined. Fix and add additional test cases matching Snapcraft 6.x tests and results.
-----
CRAFT-1377
=> filters: fix stage/prime filter combination

.github/workflows/tests.yaml, craft_parts/executor/part_handler.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, tests/integration/lifecycle/test_chisel_lifecycle.py, tests/unit/packages/conftest.py, tests/unit/packages/test_chisel.py, tests/unit/packages/test_deb.py
This is done by using the `PullState` to "transmit" the list of slices from the pull step (that currently doesn't do anything for slices) to the build step (that does the actual cutting).
The integration test needs the "chisel" binary, so it's set to run on CI only. This required updating the workflow to use a newer version of "go" to build chisel. I then needed to revert back to the default Ubuntu 20.04 version because other tests need an older version (might be worth looking into).
In addition to the tests I also built a local `rockcraft` snap using this code, and used it to build an image containing "sliced" files.
=> unpack chisel slices

craft_parts/plugins/dotnet_plugin.py, craft_parts/plugins/go_plugin.py, craft_parts/plugins/meson_plugin.py, tests/integration/plugins/test_cmake.py, tests/integration/plugins/test_dotnet.py, tests/integration/plugins/test_go.py, tests/integration/plugins/test_meson.py, tests/integration/plugins/test_npm.py, tests/integration/plugins/test_rust.py, tests/unit/plugins/test_dotnet_plugin.py, tests/unit/plugins/test_go_plugin.py, tests/unit/plugins/test_meson_plugin.py, tests/unit/sources/test_git_source.py
Craft-parts source files are licensed under the GNU Lesser General Public License version 3.
-----
=> plugins: fix license text

Makefile, tests/integration/executor/test_callbacks.py, tests/integration/executor/test_environment.py, tests/integration/lifecycle/test_lifecycle.py, tests/unit/packages/conftest.py, tests/unit/packages/test_apt_cache.py, tests/unit/packages/test_deb.py, tests/unit/packages/test_normalize.py
The fact that the packages didn't have an `__init__.py` file made pylint
skip them altogether; therefore this commit also fixes a bunch of
linting problems.
=> lint: add missing __init__ to some test packages

craft_parts/__init__.py, craft_parts/actions.py, craft_parts/executor/part_handler.py, craft_parts/plugins/base.py, craft_parts/sequencer.py, craft_parts/sources/base.py, craft_parts/sources/local_source.py, craft_parts/state_manager/pull_state.py, craft_parts/state_manager/reports.py, craft_parts/state_manager/state_manager.py, pyproject.toml, tests/integration/lifecycle/test_lifecycle.py, tests/unit/state_manager/test_pull_state.py, tests/unit/state_manager/test_states.py, tests/unit/test_actions.py, tests/unit/test_sequencer.py
Part plugins can make better decisions on how to handle part building if they know what has been changed instead of relying solely on the current state of the filesystem and on static plugin properties defined in the project. For example, retrieving plugin-specific dependency packages could be avoided entirely if no changes were made to the files listing these dependencies, resulting in faster execution times and preventing unnecessary network access.
-----
CRAFT-1365
=> [SPIKE] many: make changed file list available to plugins

craft_parts/plugins/go_plugin.py, tests/integration/plugins/test_go.py, tests/unit/plugins/test_go_plugin.py
Instead of always calling "go generate ./...", which might fail for Go projects that don't support it, add an explicit "go-generate" option to let users specify how code is generated in their parts.
CRAFT-1406
=> plugins: add 'go-generate' GoPlugin option

craft_parts/executor/executor.py, tests/integration/lifecycle/test_overlay.py, tests/unit/executor/test_executor.py
Only mount & refresh the overlay package cache if the part has overlay-packages; otherwise we're doing extra expensive work needlessly.
-----
=> overlay: only refresh overlay packages if necessary

craft_parts/overlays/chroot.py, craft_parts/utils/os_utils.py, tests/unit/overlays/test_chroot.py, tests/unit/utils/test_os_utils.py
Device nodes won't appear correctly in a regular bind mount inside a container, so use rbind instead.
-----
CRAFT-1416
=> chroot: fix device nodes in overlay base image

craft_parts/executor/migration.py, craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/utils/file_utils.py, tests/conftest.py, tests/integration/lifecycle/test_permissions.py, tests/unit/executor/test_migration.py, tests/unit/test_permissions.py, tests/unit/utils/test_file_utils.py
The migration of part files from 'stage' to 'prime' now takes into account the part's 'permissions' definition. This means forwarding the permissions lists all the way down to 'link_or_copy()'.
-----
(CRAFT-1442)
=> migration: support Permissions when migrating files

craft_parts/executor/environment.py, craft_parts/executor/step_handler.py, tests/unit/executor/test_environment.py, tests/unit/executor/test_step_handler.py
-----
Separate environment setup from the build script.  Used by https://github.com/snapcore/snapcraft/pull/3951.
~TODO - add unit tests~
(CRAFT-1411)
=> executor: separate environment setup from build script

craft_parts/errors.py, craft_parts/executor/collisions.py, craft_parts/permissions.py, tests/unit/executor/test_collisions.py, tests/unit/test_errors.py, tests/unit/test_permissions.py
Two paths are considered to be colliding if they both have permissions definitions. The definitions are not "evaluated" to see if they possibly match (that is, if both sets of definitions would generate the same result) for simplicity, but this can be improved in the future.
-----
=> executor: take permissions into account for collisions

craft_parts/__init__.py, craft_parts/actions.py, craft_parts/executor/part_handler.py, craft_parts/plugins/base.py, craft_parts/sequencer.py, craft_parts/sources/base.py, craft_parts/sources/local_source.py, craft_parts/state_manager/pull_state.py, craft_parts/state_manager/reports.py, craft_parts/state_manager/state_manager.py, pyproject.toml, tests/integration/lifecycle/test_lifecycle.py, tests/integration/lifecycle/test_plugin_changesets.py, tests/unit/state_manager/test_pull_state.py, tests/unit/state_manager/test_states.py, tests/unit/test_actions.py, tests/unit/test_sequencer.py
Part plugins can make better decisions on how to handle part building if they know what has been changed instead of relying solely on the current state of the filesystem and on static plugin properties defined in the project. For example, retrieving plugin-specific dependency packages could be avoided entirely if no changes were made to the files listing these dependencies, resulting in faster execution times and preventing unnecessary network access.
-----
=> many: make changed file list available to plugins

tests/unit/sources/test_git_source.py
Adding "-c protocol.file.allow=always" on the test is fine because we're manipulating repos created by the test itself (so no security issue).
-----
=> tests: re-enable git submodule test

docs/parts_steps.rst
The content is a bit bare and possibly in the wrong place, but we can build on it and move it around if necessary. The idea is that this can eventually be referenced by the craft applications.
-----
=> docs: add docs for permissions in parts

.github/workflows/tests.yaml, craft_parts/plugins/go_plugin.py, tests/unit/plugins/test_go_plugin.py
This is needed for a proper Chisel integration test, and it's also healthy to run the tests on the latest LTS. I did uncover an issue with the `GoPlugin` (`go mod download` semantics changed) and discovered that the overlay smoke test doesn't work (at least, not out-of-the-box). It's a TODO for now because it'll take some investigating but we should look into it soon
=> Add ubuntu-22.04 to CI runners

craft_parts/packages/deb.py, tests/integration/lifecycle/test_chisel_lifecycle.py, tests/unit/packages/test_chisel.py
Chisel only works in some Ubuntu versions (currently 22.04 and 22.10),
and instead of trying to block invalid calls let's just let the tool's
error propagate up the call stack. This way we can be a bit 'future
proof' for when new Ubuntu versions are supported.
(CRAFT-1407)
=> packages: drop release from chisel command line

craft_parts/executor/part_handler.py, craft_parts/executor/step_handler.py, craft_parts/infos.py, tests/integration/executor/test_callbacks.py, tests/unit/test_infos.py
Add build attributes and step execution state to the part information passed to post-step callbacks. This allows further processing of migrated files according to part properties set by the user.
-----
=> info: pass build attributes and state to post-step callback

craft_parts/executor/executor.py
-----
An extra set of parenthesis were misformatting a log message:
```
2022-11-22 16:58:02.517 ('The following snaps are required but not installed as the application is running inside docker or podman container: %s.\nPlease ensure the environment is properly setup before continuing.\nIgnore this message if the appropriate measures have already been taken.', 'core22')
```
```
2022-11-22 17:01:16.204 The following snaps are required but not installed as the application is running inside docker or podman container: core22.
Please ensure the environment is properly setup before continuing.
Ignore this message if the appropriate measures have already been taken.
```
=> executor: fix formatting of log message for missing snaps in container

tests/unit/sources/test_git_source.py
Fix submodule handling in the git source unit test. Adding "-c protocol.file.allow=always" on the test is fine because we're manipulating repos created by the test itself (so no security issue).
Co-authored-by: Callahan <callahan.kovacs@canonical.com>
Co-authored-by: Tiago Nobrega <tiago.nobrega@canonical.com>
=> tests: backport git submodule test fix

craft_parts/sources/git_source.py, tests/unit/sources/test_git_source.py
Add the plus symbol to valid git protocol scheme to allow entries using `git+ssh://`. This is allowed in Snapcraft 6 and displayed in Launchpad for git repos.
-----
=> sources: allow plus symbol in git url scheme (#321)

.github/workflows/tests.yaml, craft_parts/plugins/plugins.py, craft_parts/plugins/scons_plugin.py, tests/integration/plugins/test_scons.py, tests/integration/plugins/test_scons/SConstruct, tests/integration/plugins/test_scons/hello.c, tests/unit/plugins/test_scons_plugin.py
This plugin builds SCons projects and is heavily based on Snapcraft's core18 plugin. Remarks:
- The plugin builds artifacts through two commands: "scons" and "scons install". This assumes that "install" is a valid target in the source's SConstruct file.
- Since there is no "official" way to configure the installation dir for SCons-generated artifacts, the plugin assumes the common convention of setting the DESTDIR environment variable to the part's install dir.
-----
CRAFT-1418
=> plugins: add SConsPlugin

craft_parts/overlays/layers.py, pyproject.toml
ruff is a newish tool and it's getting a lot of new releases; we don't currently pin it and the latest versions need two fixes: be more permissive with temporary dirs in tests, and mark that hashlib.sha1() is not being used for security.
-----
=> linters: fix new ruff issues

docs/requirements.txt
The doc generation from code (via autodoc) is currently broken because sphinx-autodoc-typehints was interacting badly with Pydantic; update sphinx-autodoc-typehints to a newer version to fix this.
-----
=> docs: update sphinx-autodoc-typehints

craft_parts/executor/executor.py, tests/unit/executor/test_executor.py
Fix bad logic in the executor cleaning that could lead to lifecycle directories that should be cleaned unexpectedly remaining after clean is issued. Thanks to Facundo Batista for spotting this bug, fixes #329.
-----
=> executor: fix directory cleaning

craft_parts/plugins/ant_plugin.py, craft_parts/plugins/base.py, tests/unit/plugins/test_ant_plugin.py
Add a common base class for plugins that build Java projects. This is currently used by the Ant plugin, but it should be also used by the upcoming Maven plugin.
-----
=> plugins: add base class for java-related plugins

pyproject.toml
PLR2004 is "Magic value used in comparison, consider using a constant". This is triggering for things like expected messages in tests, so there were over 600 instances in craft-parts.
-----
=> linters: add PLR2004 to ruff ignore

craft_parts/executor/executor.py, craft_parts/executor/part_handler.py, craft_parts/lifecycle_manager.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, tests/unit/executor/test_part_handler.py, tests/unit/test_lifecycle_manager.py
Stage package tracking is used Snapcraft to add a list of primed stage packages to the manifest file when `--enable-manifest` is used. This is implemented using extended file attributes in Linux.
Making stage package tracking optional brings in a number of advantages: it allows other applications such as Rockcraft and Charmcraft to run faster and consume less resources, and also allows work dirs on tmpfs when package tracking is disabled (e.g. when configuring the default lxd profile for application projects to mount `/tmp` and `/root` as tmpfs).
-----
=> states: make stage package tracking optional

craft_parts/plugins/ant_plugin.py, craft_parts/plugins/autotools_plugin.py, craft_parts/plugins/cmake_plugin.py, craft_parts/plugins/dotnet_plugin.py, craft_parts/plugins/dump_plugin.py, craft_parts/plugins/go_plugin.py, craft_parts/plugins/make_plugin.py, craft_parts/plugins/maven_plugin.py, craft_parts/plugins/meson_plugin.py, craft_parts/plugins/nil_plugin.py, craft_parts/plugins/npm_plugin.py, craft_parts/plugins/python_plugin.py, craft_parts/plugins/rust_plugin.py, craft_parts/plugins/scons_plugin.py
Use the `@override` decorator to ensure plugin methods correctly overrode an inherited method.
-----
=> plugins: verify plugin method override

setup.py
Ensure that ruff only gets updated by renovate or explicitly in PRs. This will prevent random CI breakages until ruff is stable.
Related: https://github.com/canonical/starbase/pull/21
-----
=> lint: specify a single ruff version

craft_parts/sources/local_source.py, tests/unit/sources/test_local_source.py
Don't create a cumulative list of patterns to ignore when processing local sources, or the list can become quite large with repetitions of the same patterns.
This can be further refactored to rename confusing variable names and remove unused code. This commit only fixes the cumulative list building issue, other issues will be addressed in separate PRs.
-----
=> sources: fix ignore patterns in local sources

tests/integration/__init__.py, tests/integration/plugins/test_maven.py
-----
I came across this while running the integration tests. As is, the maven test succeeds when running all tests in order, but fails when run without running the ant test. The change in `test_maven.py` fixes the test so it can run independently, and the change in `__init__.py` ensures that cached functions get their caches cleared after each integration test, keeping them more independent.
=> tests: Ensure maven test sets environment

craft_parts/__init__.py, craft_parts/errors.py, craft_parts/features.py, craft_parts/lifecycle_manager.py, craft_parts/parts.py, craft_parts/sequencer.py, craft_parts/state_manager/state_manager.py, craft_parts/utils/__init__.py, tests/integration/features/test_lifecycle_no_overlay.py, tests/unit/test_errors.py, tests/unit/test_features.py, tests/unit/test_lifecycle_manager.py, tests/unit/test_parts.py
Craft-parts can now specify features that can be enabled or disabled to change its behavior in certain scenarios. This change also includes a minimally intrusive implementation of the overlay feature, which inhibits the generation of overlay actions when this feature is disabled by the application.
-----
CRAFT-1531
=> features: introduce craft-parts features

craft_parts/errors.py, craft_parts/executor/step_handler.py, craft_parts/infos.py, craft_parts/lifecycle_manager.py, craft_parts/main.py, craft_parts/parts.py, craft_parts/plugins/__init__.py, craft_parts/plugins/base.py, craft_parts/plugins/dump_plugin.py, craft_parts/plugins/nil_plugin.py, setup.py, tests/integration/test_main.py, tests/unit/common_plugins.py, tests/unit/executor/test_step_handler.py, tests/unit/test_lifecycle_manager.py, tests/unit/test_parts.py
The first commit has @cmatsuoka 's original code with some minor linting by me. The second commit has the tests I added.
One thing we should maybe discuss is this `strict`/`offline` "duality". Really what a "strict" plugin currently means is that it does offline builds, but is that definition something that we envision changing in the future? Should we use "strict" throughout the codebase?
(CRAFT-1587)
=> plugins: implement strict/offline plugins

.github/workflows/tests.yaml
-----
This should work aroud the issue with the node integration tests from the image change to default to node 18
=> ci: set default node version to 16

craft_parts/plugins/python_plugin.py, tests/integration/plugins/test_python.py, tests/unit/plugins/test_python_plugin.py
The location of the Python interpreter executable can depend on application-specific parameters that cannot be determined by a generic parts plugin. To address that, allow applications to subclass and override methods in the Python plugin in order to use custom logic to set the interpreter location.
Co-authored-by: Tiago Nobrega <tiago.nobrega@canonical.com>
-----
CRAFT-1629
=> plugins: refactor python plugin for subclassing

craft_parts/overlays/chroot.py, tests/fake_snapd.py, tests/unit/overlays/test_chroot.py
Address shared mount issues affecting /dev mount in chroots. This is a result of https://github.com/lxc/lxc/pull/4229 (container rootfs became a shared mount, meaning that unmounts propagates through the shared group and original mounts are unmounted too).
See https://github.com/canonical/rockcraft/issues/195 for details.
-----
=> chroot: mark /dev mount as private

craft_parts/sources/sources.py, tests/unit/sources/test_sources.py
By default, the launchpad instruction for clone will contain `git+ssh`
When cloning launchpad repo without defining source-type, I will get `Failed to pull source: unable to determine source
type of git+ssh://git.launchpad.net/<TEAM>/<PROJECT>+git/<REPO>`
-----
=> sources: add 'git+ssh:' for 'git' source-type

setup.py
-----
Pydantic was frozen at 1.9 due a pydantic-yaml dependency that has been resolved upstream. https://github.com/canonical/craft-parts/pull/221/commits/b42526df48de47857ce807336da3eed4ef14f017
=> deps: loosen pydantic dependency

craft_parts/sources/local_source.py
Fixes #416
Removing items from a list while iterating though that list (in a for loop) causes items in the list to be skipped in the for loop
=> Remove items from `directories` list after iteration

craft_parts/sequencer.py, craft_parts/state_manager/reports.py, craft_parts/state_manager/step_state.py, tests/unit/test_sequencer.py
Add missing plugin properties to action planning to reflect the
complete state persisted after the previous execution run.
-----
=> sequencer: use plugin properties in action planning

craft_parts/plugins/python_plugin.py, tests/integration/plugins/test_python.py, tests/integration/plugins/test_python_pyproject_toml/mytestpyprojecttoml/__init__.py, tests/integration/plugins/test_python_pyproject_toml/pyproject.toml, tests/unit/plugins/test_python_plugin.py
Python projects move to pyproject.toml[0] instead of using setup.py so add support to craft-parts so snaps can be build using the python plugin.
[0]
https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
-----
=> plugins: add support for pyproject.toml projects (lp:#2008237)

setup.py, tests/conftest.py
=> requirements: pin urllib3 version to prevent request problems

craft_parts/executor/part_handler.py, tests/unit/executor/test_part_handler.py, tests/unit/features/overlay/test_executor_part_handler.py
The working directories for the pull and build steps should
also be set accordingly when source-subdir is set.
-----
=> executor: fix subdir in pull and build steps

craft_parts/plugins/python_plugin.py, tests/integration/plugins/test_python.py, tests/unit/plugins/test_python_plugin.py
This commit handles the case where the venv symlinks must be removed, but a part-provided Python interpreter *must* be present. This is done by deferring the symlink removal to the end of the build, so that the existing check for a valid interpreter can be performed.
This is to address the "Rockcraft/ubuntu" case in the following table of existing scenarios:
That case is particularly bad because the "failure to have the build fail" results in a ROCK that is completely unusable, because of an additional (usrmerge) bug that will be addressed in a separate PR/issue.
CRAFT-1725
=> plugins: better checking for needed payload python

craft_parts/callbacks.py, craft_parts/executor/executor.py, craft_parts/lifecycle_manager.py, craft_parts/packages/base.py, craft_parts/packages/deb.py, tests/integration/plugins/test_python.py, tests/unit/packages/test_deb.py, tests/unit/test_callbacks.py
Craft Parts includes mechanisms to filter out stage package dependencies
in snap bases. This is now deprecated, and a function providing an
explicit list of exclusions should be registered by the application
as a callback.
-----
CRAFT-1724
=> callbacks: add callback to explicitly list base packages

craft_parts/callbacks.py, craft_parts/executor/executor.py, tests/conftest.py, tests/unit/executor/test_executor.py, tests/unit/test_callbacks.py
This new callback is called by the Executor after the overlay's package cache layer is mounted, but before the package list is actually refreshed. The main purpose is to give applications a chance to configure the Apt installation in the overlay (e.g. add/remove package repositories).
-----
=> callbacks: add callback to configure overlay package layer

tests/unit/sources/test_snap_source.py
-----
[Pyright 1.1.312](https://github.com/microsoft/pyright/releases/tag/1.1.312) now type-checks kwargs. This started causing the following error:
```
pyright setup.py craft_parts tests
/home/runner/work/craft-parts/craft-parts/tests/unit/sources/test_snap_source.py
/home/runner/work/craft-parts/craft-parts/tests/unit/sources/test_snap_source.py:49:79 - error: Argument of type "str" cannot be assigned to parameter "source_depth" of type "int | None" in function "__init__"
Type "str" cannot be assigned to type "int | None"
"str" is incompatible with "int"
Type cannot be assigned to type "None" (reportGeneralTypeIssues)
/home/runner/work/craft-parts/craft-parts/tests/unit/sources/test_snap_source.py:49:79 - error: Argument of type "str" cannot be assigned to parameter "project_dirs" of …
```
=> lint: use correct types for SnapSource test

docs/base/overlay_parameters.rst
-----
This example `parts.yaml` does not work because it uses underscores instead of hyphens.
=> docs: fix yaml in examples

.github/workflows/tests.yaml, README.md, craft_parts/packages/apt_cache.py, setup.py, tox.ini
-----
OK, so this is a different mechanism for hopefully making the python-apt dependency easier to deal with.
1. `python-apt` is made an optional dependency with a graceful notification about it.
2. Several optional extras are added to specify a specific package for developer convenience.
Unfortunately, the second would not work without the first, at least not in any way I could figure out, as `python-apt` without a specified location would get an attempted install before the version with the specified location (rather than being deduplicated).
=> deps: make python-apt dependency optional

craft_parts/__init__.py, craft_parts/parts.py, tests/unit/features/overlay/test_parts.py
The helper acts as an early query of whether a given part spec uses
overlays (through either overlay-packages, or overlay-scripts, etc).
=> parts: add a helper to query overlay use

craft_parts/sources/snap_source.py
Some parameters like `source_submodules` are passed when source
is instantiated. Constructor needs to handle those parameters.
=> source: snap: Forward unmatched parameters

setup.py
Pydantic 2.0.0 has recently been released and craft_parts needs work to support it.
-----
=> packaging: pin Pydantic to <2.0.0

craft_parts/plugins/python_plugin.py, tests/integration/plugins/test_python.py, tests/unit/plugins/test_python_plugin.py
This commit updates the Python plugin to be more restrictive when looking for the interpreter in the parts' payload: if the venv is created using "python3.10", then that exact version of Python must be found in the payload in order to be usable.
In addition to avoiding issues from incompatible versions, this handles cases like the Python 3.6 package (from the deadsnakes ppa) that has both a "python3.6" and a "python3.6m" binaries by default.
-----
=> plugins: be more specific in search for payload Python

tests/unit/packages/test_apt_cache.py
-----
This week, a unit test started [failing](https://github.com/canonical/craft-parts/actions/runs/5536668539/jobs/10119585228?pr=493#step:8:179) on the Ubuntu 22.04 CI runner:
```
FAILED tests/unit/packages/test_apt_cache.py::TestAptStageCache::test_stage_packages - AssertionError: assert ['gcc-13-base...', 'pciutils'] == ['libpci3', 'pciutils']
At index 0 diff: 'gcc-13-base' != 'libpci3'
Left contains 2 more items, first extra item: 'libpci3'
Full diff:
- ['libpci3', 'pciutils']
+ ['gcc-13-base', 'libgcc-s1', 'libpci3', 'pciutils']
```
I'm not sure what changed or if this is the right solution...
=> tests: add jammy packages to stage package apt cache

tests/unit/packages/test_apt_cache.py
New packages are marked for installation on Jammy - see #495
Signed-off-by: Callahan Kovacs <callahan.kovacs@canonical.com>
(cherry picked from commit dcdab5926caecd1848b6c3c0db9decf8f8ed02cd)
-----
CI fixed in combination with #511. This is visible in the CI results from #513.
=> tests: add jammy packages to stage package apt cache (#494)

craft_parts/utils/partition_utils.py, tests/unit/utils/test_partition_utils.py
-----
Adds a utility function that takes a filepath and returns a partition-compatible filepath.
(CRAFT-1845)
=> partitions: add utility to make partition compatible filepaths

craft_parts/executor/executor.py, craft_parts/executor/part_handler.py, tests/integration/test_logging.py
Add informational messages to distinguish when we're installing build-packages, installing build-snaps, updating the overlay base system and fetching stage-packages, as these are potentially time-consuming operations and with the exception of fetching the stage-packages they all happen before we even start executing lifecycle steps.
Fixes #508
-----
=> executor: add prologue INFO-level log messages

craft_parts/infos.py, craft_parts/sequencer.py, tests/integration/lifecycle/test_craftctl.py, tests/unit/test_infos.py
Project variables exist only in the part scope and should be ignored
in other parts' states. In the existing implementation these values
are persisted in each part, which leads to double assignment errors
when a step is executed for parts in a order that's different from
the previous execution (see example in LP #1831135).
There are different ways to address this issue, the current fix
tries to be minimally disruptive by just ignoring persisted values
when reloading the state. We can refactor this code later to have
a cleaner implementation.
-----
=> sequencer: only load project vars in adopting part (#509)

craft_parts/executor/part_handler.py, craft_parts/packages/deb.py
This commit is a workaround for a current bad interaction between the way we perform overlay operations (a chroot in a multiprocess-created subprocess) and the way craft applications indicate progress on the cli (a spinner in a thread).
The consequence of the bad interaction is that trying to write an info message to the terminal ends up deadlocking the main thread in the subprocess because the thread that could unblock it does not exist.
Instead, log the message as 'debug' instead of 'info', and add a main- process-side 'info' message to communicate that overlay packages are being fetched.
-----
=> packages: don't write info logs in overlays

craft_parts/executor/part_handler.py, craft_parts/packages/deb.py
This commit is a workaround for a current bad interaction between the
way we perform overlay operations (a chroot in a multiprocess-created
subprocess) and the way craft applications indicate progress on the
cli (a spinner in a thread).
The consequence of the bad interaction is that trying to write an info
message to the terminal ends up deadlocking the main thread in the
subprocess because the thread that could unblock it does not exist.
Instead, log the message as 'debug' instead of 'info', and add a main-
process-side 'info' message to communicate that overlay packages are
being fetched.
-----
=> packages: don't write info logs in overlays (#535)

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, docs/conf.py, setup.py
* Don't write log information in overlays (workaround for craft-cli issue)
-----
=> Release 1.24.1

tests/integration/lifecycle/test_chisel_lifecycle.py
Chisel is now supported on Ubuntu 20.04.
-----
=> test(chisel): update supported platforms

craft_parts/plugins/rust_plugin.py, tests/integration/lifecycle/test_chisel_lifecycle.py, tests/unit/plugins/test_rust_plugin.py
-----
The new plugin will install the Rustup toolchain by default (opt-out possible) and also makes it more intelligent.
Three new options have been added:
- One option for enabling LTO (more optimized binary)
- One option for specifying Rust toolchain channel/version
- One option for disabling default features in the Rust crate
=> plugins/rust_plugin: rewrite the plugin to improve UX

craft_parts/executor/environment.py, tests/integration/executor/test_environment.py, tests/integration/executor/test_environment_overlay.py, tests/unit/executor/test_environment.py, tests/unit/features/overlay/test_executor_environment.py
-----
Sort project variables before replacement, such that `$CRAFT_ARCH_TRIPLET_BUILD_{ON|FOR}` are replaced before `$CRAFT_ARCH_TRIPLET`.
Fixes #541
(CRAFT-2029)
=> fix(environment): sort project variables before replacement

craft_parts/lifecycle_manager.py, tests/unit/test_lifecycle_manager.py
Raise an error if a part depends on a non-existing part name.
Fixes: #539
-----
Example output from application:
```
$ snapcraft --destructive-mode 
Initializing parts lifecycle :: A part named 'trololo' is not defined in the parts list.
Review the parts definition and make sure it's correct.
```
=> fix(parts): validate part dependency name

craft_parts/plugins/rust_plugin.py, setup.py
-----
This pull request fixes the following issues:
- Typing checking issues with the `rust_channel` override. This is unnecessary because some part of the configuration check is done in the validation step, making it impossible to set both `rust-deps` and `rust-channel` to a valid value (which will install two different Rust toolchains).
- Properly removes the compiler plugins. Rust plugin can now identify and remove the compiler plugins installed in the final staging area. Rust compiler will embed two different metadata into the compiler plugin. The craft-parts Rust plugin recognizes the compiler plugin by checking the dynamic symbol inserted into the `.data.rel.ro` section.
---
This pull request fixes #559.
=> rust_plugin: multiple fixes 

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, docs/conf.py, setup.py
* Fix compiler plugin priming in Rust plugin
* Fix redundant channel override in Rust plugin
* Fix validation of part dependency names
* Fix expansion of environment variables
=> Release 1.25.2

craft_parts/packages/deb.py, tests/integration/lifecycle/test_chisel_lifecycle.py, tests/unit/packages/test_chisel.py
(this is the same code as before, but now cherry-picked off of `hotfix/1.26.1`)
When stage debs are unpacked, we "normalize" the contents to do things like fix absolute symlinks (as absolute links would point outside the lifecycle environment). Do the same for cut chisel slices too.
Fixes #578
-----
=> fix(deb): normalize chisel slices

craft_parts/utils/partition_utils.py, craft_parts/utils/path_utils.py, tests/unit/features/partitions/conftest.py, tests/unit/features/partitions/executor/test_migration.py, tests/unit/features/partitions/executor/test_part_handler.py, tests/unit/features/partitions/executor/test_step_handler.py, tests/unit/features/partitions/test_parts.py, tests/unit/utils/test_path_utils.py
-----
Handle namespaced partitions in utility functions, `get_partitioned_path()`, `get_partition_and_path()`, `get_stage_dir()`, and `get_prime_dir()`.
#596 
(CRAFT-2303)
=> feat(partitions): handle namespaced partitions in utils

.github/renovate.json5, setup.py
Also removes from renovate config until we can remove Python 3.7
One of two PRs that will fix renovate. https://github.com/canonical/craft-parts/pull/589
-----
=> chore(deps): loosen mypy requirement

craft_parts/plugins/ant_plugin.py, tests/unit/plugins/test_ant_plugin.py
Add proxy support to ant plugin
Currently, this is a limitation to running remote builds in the launchpad as those builds require proxy support.
=> plugins: ant: add proxy support

craft_parts/plugins/ant_plugin.py, tests/unit/plugins/test_ant_plugin.py
Honor the proxy environment variable in ant projects.
-----
=> fix(plugins): add proxy support to ant plugin (#579)

.github/workflows/tests.yaml
A new version of chisel-releases breaks compatibility with chisel binaries older than v0.8.1.
Ref: https://github.com/canonical/rockcraft/pull/449
-----
We'll also need to cherry-pick this into any live hotfix branch
=> chore(ci): update chisel

tests/unit/overlays/test_chroot.py, tests/unit/packages/test_base.py
-----
- `tests/unit/packages/test_base.py::TestOriginStagePackage::test_mark_origin_stage_package` was creating `.tests-xattr-test-dir/` in the cwd
- `tests/unit/overlays/test_chroot.py::TestChroot::test_runner` was creating `foo.txt` in the cwd
=> test: use `new_dir` fixture

setup.py
-----
`overrides` 7.6.0 introduced a bug: https://github.com/mkorpela/overrides/issues/121
A handful of python plugin tests are failing with:
```
FAILED tests/integration/plugins/test_python.py::test_python_plugin_no_system_interpreter[True] - TypeError: test_python_plugin_no_system_interpreter.<locals>.MyPythonPlugin._get_system_python_interpreter: No super class method found
```
due to how the tests override superclass functions:
```
class MyPythonPlugin(craft_parts.plugins.plugins.PythonPlugin):
@override
def _get_system_python_interpreter(self) -> Optional[str]:
return None
```
Our options are:
1. Merge this PR
2. Use the workaround described in the bug linked above
3. Wait for a fix in `overrides`
=> build(deps): pin overrides!=7.6.0

craft_parts/executor/part_handler.py, craft_parts/parts.py, tests/integration/test_logging.py
-----
I was getting some PyRight errors when trying to create a `PartSpec` with just a `plugin` value:
```python3
foo = PartSpec(plugin="foo")
```
PyRight gives me this error:
```
error: Arguments missing for parameters "organize", "overlay", "stage", "prime" (reportCallIssue)
```
It could also be PyRight misinterpreting something, but using `default_value` instead of `default` for mutable types seems like a good idea anyway, and as a side effect seems to silence PyRight's error report.
Conceptually, the `pydantic.Field`'s `default` vs `default_factory` have the same semantic as Python's own [`dataclasses.field`](https://docs.python.org/3/library/dataclasses.html#dataclasses.field) class, which says about `default_type`:
>  Among other purposes, this can be used to specify fields with …
=> fix(parts): set field defaults using default_factory

craft_parts/plugins/rust_plugin.py, docs/base/rust_plugin.rst, tests/unit/plugins/test_rust_plugin.py
-----
This pull request adds a few more options to the existing Rust plugin. It also switches to the `rustup` Snap instead of the ad-hoc installation method.
=> feat(rust_plugin): use `rustup` snap and more options

craft_parts/executor/part_handler.py, craft_parts/parts.py, tests/integration/test_logging.py
-----
Cherry-pick #629 into the `feature/namespaced-partitions` branch.  Despite the commit header, it has the new `black` 2024 changes and a fix for a failing integration test exposed after pytest 8 was released.
=> fix(parts): set field defaults using default_factory (#629)

.github/workflows/tests.yaml
Version 0.8.1 was meant as a temporary stopgap; version 0.9.0 has the actual support for the breaking changes in chisel-releases.
-----
=> ci: update Chisel version again

docs/base/part_properties.rst, docs/explanation/filesets.rst
Was looking for how the `prime` and `stage` part properties take glob-like inclusion and exclusion patterns, but the docs didn't point to the fact that these are "filesets".
Add a link to the fileset specification explanation, so that people looking for all the possible fileset-specific ways of specifying files to include and exclude can find it easily.
Also, "at least item" -> "at least 1 item"
=> docs: Link filesets specification from part properties

pyproject.toml
-----
This pull request adds the previously removed Pylint rules back to Ruff (since Ruff recently added support for them).
The commented-out rule is currently a work in progress upstream: https://github.com/astral-sh/ruff/pull/9844.
=> chore(linter): refine ruff configurations

craft_parts/executor/organize.py, craft_parts/executor/part_handler.py, tests/unit/executor/test_organize.py, tests/unit/features/partitions/executor/test_organize.py
Fixes an issue discovered via canonical/snapcraft#4654 where `organize_files()`
would organize in the cwd instead of the project's base_dir.
The problem was that `organize_files()` was redefining a part's install directories
incorrectly by creating relative filepaths.
To fix this, organize_files now accepts the part's install directories instead of
redefining them.
-----
=> fix(organize): use the part's install directories (#689)

docs/common/craft-parts/reference/plugins/go_plugin.rst, docs/reference/plugins.rst
This includes an example because, contrary to plugins that have a runtime component, the go plugin is build-time only - this example applies identically to Snapcraft, Rockcraft, etc.
-----
=> docs: add docs for 'go' plugin

docs/common/craft-parts/reference/plugins/scons_plugin.rst, docs/reference/plugins.rst
=> feat(docs): scons plugin reference

craft_parts/plugins/npm_plugin.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/common/craft-parts/reference/plugins/npm_plugin.rst, docs/reference/plugins.rst, tests/integration/plugins/test_npm.py, tests/unit/plugins/test_npm_plugin.py
-----
This pull request refactors the NPM plugin and contains the following changes:
* npm-node-version option now accepts an NVM-style version identifier
* Move Node.js download to pull commands
* Verify SHA256 checksums after the Node.js download
* Use new-style npm-install commands if `npm` version is newer than ~~8.x~~ 10.x
* Set `NODE_ENV` to production by default
* Add documentation
=> feat(plugin): Refactor NPM plugin

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, setup.py
- Refactored npm plugin
- npm-node-version option now accepts a NVM-style version identifier
- Move Node.js download to pull commands
- Verify SHA256 checksums after node.js download
- Use new-style npm-install commands if npm version is newer than 8.x
- Set NODE_ENV to production by default
- New and improved documentation
- Add go plugin reference
- Add nil plugin reference
- Add make pliugin reference
- Add autotools plugin reference
- Add cmake plugin reference
- Add scons plugin reference
- Add ant plugin reference
- Add dotnet plugin reference
- Add meson plugin reference
- Documentation fixes
=> Release 1.31.0

setup.py
-----
This pull request temporarily limits `requests` version to avoid a breaking change in the behaviour that renders craft_parts unusable.
See also:
- https://github.com/psf/requests/issues/6707
- https://github.com/canonical/pylxd/issues/579
- https://github.com/docker/docker-py/issues/3256
=> fix(setup.py): temporarily limits `requests` version to fix CI

.github/workflows/tests.yaml, craft_parts/lifecycle_manager.py, craft_parts/overlays/layers.py, craft_parts/packages/yum.py, craft_parts/sequencer.py, tests/integration/lifecycle/test_lifecycle.py, tests/integration/lifecycle/test_lifecycle_overlay.py, tests/integration/lifecycle/test_overlay.py, tests/integration/sequencer/test_sequencer.py, tests/integration/sequencer/test_sequencer_overlay.py, tests/integration/test_main.py, tests/unit/test_sequencer.py
Instead of implicitly cleaning and re-executing steps when a part name
is specified, only do it when explicitly requested by the user.
Applications must set the `rerun` argument accordingly when planning
the lifecycle execution.
Fixes canonical/snapcraft#4806
-----
=> fix(sequencer): rerun steps only if explicitly requested

craft_parts/infos.py, craft_parts/packages/deb.py, tests/integration/plugins/test_ant.py, tests/integration/plugins/test_autotools.py, tests/integration/plugins/test_maven.py, tests/integration/test_logging.py, tests/unit/packages/test_deb.py, tests/unit/test_errors.py
Instead of relying on a user-supplied environment variable, check for
the user id and skip running ``apt update`` if not running as root.
-----
=> feat(deb): only run apt update as superuser

craft_parts/packages/deb.py, tests/unit/packages/test_deb.py
**Note:** This PR has 2 commits, but that's only to make the review easier: the first commit copies the list of core22 ignored packages into core24's, and then the second commit updates that list to reflect the contents of core24. So if you look at the second commit only you'll see just the diff.
---------
This list is updated based on the packages currently present on
/snap/core24/current/usr/share/snappy/dpkg.list. Note that some
packages are added, but mostly these are removals.
=>  fix: add list of ignore packages in core24

craft_parts/packages/deb.py, docs/changelog.rst, tests/unit/packages/test_deb.py
=> chore(merge): '1.30.1' into 'main'

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, setup.py
-----
New 1.31.x release to pull in the stage-packaging hotfix from 1.30.1.
I need this for snapcraft 8.3, which uses craft-parts 1.31
=> build: bump version to 1.31.1

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, setup.py
-----
I landed a PR for 1.31.1 before realizing there were commits on `main` that had new features.  
This PR bumps to 1.32.0 and removes 1.31.1 from the changelog since it was never tagged or released.
=> build: bump version to 1.32.0

.github/workflows/tests.yaml
I don't know why this started happening just recently, but it looks like the CI
runner does not have the `pkg-config` (a rust plugin dep) package installed.
Instead, it looks like it has `pkgconf`, pulled in by `r-base-dev`. I say this
because those get removed when we explicitly install `pkg-config`:
```
...
The following packages will be REMOVED:
pkgconf r-base-dev
The following NEW packages will be installed:
autopoint cmake cmake-data dh-elpa-helper gperf help2man libjsoncpp25
librhash0 ninja-build pkg-config qt5-qmake qt5-qmake-bin qtchooser scons
0 upgraded, 14 newly installed, 2 to remove and 41 not upgraded.
...
```
=> chore(ci): install rust plugin dependencies

craft_parts/parts.py, craft_parts/plugins/__init__.py, craft_parts/plugins/ant_plugin.py, craft_parts/plugins/autotools_plugin.py, craft_parts/plugins/base.py, craft_parts/plugins/cmake_plugin.py, craft_parts/plugins/dotnet_plugin.py, craft_parts/plugins/dump_plugin.py, craft_parts/plugins/go_plugin.py, craft_parts/plugins/make_plugin.py, craft_parts/plugins/maven_plugin.py, craft_parts/plugins/meson_plugin.py, craft_parts/plugins/nil_plugin.py, craft_parts/plugins/npm_plugin.py, craft_parts/plugins/properties.py, craft_parts/plugins/python_plugin.py, craft_parts/plugins/qmake_plugin.py, craft_parts/plugins/rust_plugin.py, craft_parts/plugins/scons_plugin.py, docs/common/craft-parts/craft-parts.wordlist.txt, tests/integration/lifecycle/test_plugin_changesets.py, tests/integration/lifecycle/test_plugin_property_state.py, tests/integration/plugins/test_application_plugin.py, tests/integration/plugins/test_validate_environment.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_dump_plugin.py, tests/unit/plugins/test_plugins.py, tests/unit/plugins/test_properties.py, tests/unit/plugins/test_validator.py
-----
This does several related things:
1. Removes the vestigial `PluginModel` from `craft_parts.plugins.base`
2. Combines `PluginPropertiesModel` and `PluginProperties` (which didn't need separation anymore)
3. Makes the `unmarshal` method of `PluginProperties` usable by all plugins (and deletes the unnecessary overrides)
=> chore!: restructure plugin models

craft_parts/plugins/base.py
Ruff 0.5 complains about the for loop
-----
=> chore: simplify extract_plugin_properties

docs/common/craft-parts/explanation/how_parts_are_built.rst, docs/common/craft-parts/explanation/overlay_parameters.rst, docs/common/craft-parts/explanation/overlays.rst, docs/common/craft-parts/explanation/parts.rst, docs/common/craft-parts/reference/part_properties.rst, docs/explanation/index.rst
-----
This PR is part of series of proofreading Rockcraft and Craft Parts documentation, making it up-to-date and conforming to standards, and adding/fixing sections and links where necessary.
=> docs: fix explanation pages

docs/common/craft-parts/explanation/how_parts_are_built.rst, docs/common/craft-parts/explanation/parts.rst, docs/conf.py
-----
The reference to the overlay explanation added in #765 is a problem for applications that exclude the overlay explanation page.
See downstream usage: https://github.com/canonical/snapcraft/pull/4948
=> docs: add labels for overlay step

craft_parts/lifecycle_manager.py, craft_parts/utils/partition_utils.py, docs/common/craft-parts/craft-parts.wordlist.txt, tests/unit/features/partitions/executor/test_environment.py, tests/unit/features/partitions/test_lifecycle_manager.py, tests/unit/features/partitions/test_parts.py, tests/unit/utils/test_partition_utils.py
-----
Allow hyphens in partitions, partition namespaces, and namespaced partitions.
Unblocks [LP#2069783](https://bugs.launchpad.net/snapcraft/+bug/2069783)
(CRAFT-3043)
=> feat: allow numbers in partition names and namespaces

setup.py
-----
Some change to the README in https://github.com/canonical/craft-parts/pull/773 started breaking PyPI uploads with twine:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.
```
Fixed with the example in https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/
Unblocks CRAFT-3043
=> build: define readme type in python metadata

craft_parts/utils/partition_utils.py, craft_parts/utils/path_utils.py, tests/unit/features/partitions/test_parts.py, tests/unit/utils/test_path_utils.py
-----
Partitions with numbers and hyphens can currently be added, but once you get into lifecycle steps the process will fail strangely - craft-parts thinks paths like `(partition-name1)` are normal paths.
(CRAFT-3031)
=> fix: partitions break when using special characters

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, docs/common/craft-parts/craft-parts.wordlist.txt, setup.py
=> chore: prepare release 2.0.0

setup.py
Not needed anymore since Pydantic 2, where we model_dump() the model and then use PyYAML directly.
-----
=> build(deps): drop unnecessary pydantic-yaml

.github/workflows/tests.yaml
This was already happening thanks to tox changes, but this does do unit tests on 3.13 on focal now too.
-----
=> ci: only use Python 3.10+

craft_parts/dirs.py, craft_parts/errors.py, docs/common/craft-parts/craft-parts.wordlist.txt
-----
Raise a custom error when a nonexistent partition is asked for, so `corncraft` can catch it more cleanly.
Depending on the stringification is fragile, but if you don't do some sort of deeper check then you could accidentally handle other `ValueError`s.
(CRAFT-3031)
=> feat(partitions): custom error for nonexistent partition

craft_parts/executor/part_handler.py, docs/common/craft-parts/craft-parts.wordlist.txt, tests/integration/features/partitions/lifecycle/test_lifecycle.py, tests/unit/executor/test_part_handler.py
This localized fix addresses the issue of stage-package tracking failing in
the presence of partitions by looking for the primed files in each partition.
This solves the most common cases but doesn't fix the issue where a given file
might be present in multiple partitions, as this needs a deeper refactoring of
the state tracking (see discussion in https://github.com/canonical/craft-parts/issues/804).
Fixes https://github.com/canonical/craft-parts/issues/804
-----
=> fix: use partitions for stage-packages tracking

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, setup.py
-----
Releasing so I can get #834 into snapcraft.
=> docs(changelog): add 2.1.0 release notes

craft_parts/plugins/npm_plugin.py, tests/unit/plugins/test_npm_plugin.py
-----
This pull request works around an issue that regressed NPM-based projects on the Launchpad auto-build system.
The issue was that the Launchpad auto-build system executed pull and build steps separately, thereby losing the shared state between them.
This is a temporary fix for the 1.33 branch.
=> fix(plugins): ensure stateless npm plugin

craft_parts/plugins/base.py
JavaPlugin provides _get_java_post_build_commands() that is called from derived classes.
/bin/java link is broken for rockcraft projects.
Split _get_java_link_commands() into _get_java_link_commands() and _get_jar_link_commands() to allow rockcraft plugins override _get_java_link_commands().
This MR addresses https://github.com/canonical/craft-parts/issues/813
-----
=> chore: split _get_java_post_build_commands

.github/renovate.json5, craft_parts/packages/snaps.py, docs/changelog.rst, docs/common/craft-parts/craft-parts.wordlist.txt, setup.py, tests/conftest.py, tests/integration/packages/test_snaps.py
=> build(deps): replace requests-unixsocket with requests-unixsocket2

craft_parts/plugins/base.py, docs/changelog.rst, tests/integration/plugins/test_python.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_poetry_plugin.py, tests/unit/plugins/test_python_plugin.py
=> fix: don't fail if the Python part has no scripts

.bumpversion.cfg, craft_parts/__init__.py, docs/changelog.rst, docs/conf.py, setup.py, tests/conftest.py, tests/integration/features/partitions/lifecycle/test_lifecycle.py, tests/integration/packages/test_snaps.py
-----
This is the same as #853 and #856, but for the 1.25 hotfix branch.
=> chore: backport unixsocket -> unixsocket2 to 1.25 for charmcraft

docs/requirements.txt
0.2.0 causes some breakages that will need attention.
-----
=> build(deps): use correct canonical-sphinx

docs/common/craft-parts/reference/plugins/poetry_plugin.rst, docs/common/craft-parts/reference/plugins/python_plugin.rst
This adds anchors to the Python and Poetry documentation to support how Charmcraft is going to use these.
-----
=> docs: add anchors to support charmcraft documentation

.github/workflows/tests.yaml, craft_parts/plugins/go_plugin.py, craft_parts/plugins/go_use_plugin.py, craft_parts/plugins/plugins.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/common/craft-parts/reference/plugins/go_plugin.rst, docs/common/craft-parts/reference/plugins/go_use_plugin.rst, docs/reference/plugins.rst, tests/integration/plugins/test_go.py, tests/integration/plugins/test_go_use.py, tests/integration/plugins/test_go_workspace/go.mod, tests/integration/plugins/test_go_workspace/go.sum, tests/integration/plugins/test_go_workspace/main.go, tests/unit/plugins/test_go_plugin.py, tests/unit/plugins/test_go_use_plugin.py
=> feat: support workspaces for go

craft_parts/plugins/poetry_plugin.py, tests/unit/plugins/test_poetry_plugin.py
If a `poetry-deps` dependent part exists, don't add poetry to the packages to install.
Fixes https://github.com/canonical/charmcraft/issues/1996
CRAFT-3687
-----
=> fix(poetry): don't install poetry with poetry-deps

craft_parts/lifecycle_manager.py, craft_parts/parts.py, tests/unit/test_parts.py
-----
This PR aims to stop chisel from being unnecessarily installed in the Rockcraft snap.
It does that by having chisel as a build snap only when the following conditions are met:
- there is at least one `part` that has slices in its `stage-packages`
- there is no `part` that has chisel in its `build-snaps`
=> feat: add chisel as a build snap when stage-packages contain slices

docs/changelog.rst, docs/conf.py
=> docs: fix linting for release tags and backfill changelog links to 2.0.0

craft_parts/plugins/rust_plugin.py, tests/unit/plugins/test_rust_plugin.py
-----
This pull request fixes the dependency validation logic regarding the "rust-deps" situation. If `rustup` is installed, then `cargo` and `rustc` will return an error code of `1` instead of `127` if no default toolchain is installed (because `cargo` and `rustc` will be shims generated by `rustup`).
Two more tests are added to verify this new validation logic.
Should fix #890.
=> fix(rust_plugin): fix dependency validation logic

craft_parts/__init__.py, craft_parts/parts.py
-----
This is add two utility functions `part_has_slices` and `part_has_chisel_as_build_snap` that takes a dictionary (representing a part's data) as an argument and determine whether the part data has slices and whether it has chisel in build-snaps, respectively.
Those functions are needed in Rockcraft, where we deal with part data dictionaries often, and converting those dictionaries to PartSpec objects will require extra code that has been already implemented internally in craft-parts.
Related work: #904
=> feat: add funcs part_has_slices and part_has_chisel_as_build_snap

docs/common/craft-parts/reference/plugins/ant_plugin.rst, docs/common/craft-parts/reference/plugins/maven_plugin.rst
Ant and maven plugin descriptions are overriden by rockcraft. Add labels to simplify documentation override.
-----
=> doc(ant,maven): add labels for description

craft_parts/sources/__init__.py, craft_parts/sources/base.py, craft_parts/sources/deb_source.py, craft_parts/sources/errors.py, craft_parts/sources/git_source.py, craft_parts/sources/rpm_source.py, craft_parts/sources/sevenzip_source.py, craft_parts/sources/snap_source.py, craft_parts/sources/sources.py, craft_parts/sources/tar_source.py, craft_parts/sources/zip_source.py, docs/Makefile, docs/changelog.rst, docs/common/craft-parts/craft-parts.wordlist.txt, docs/how-to/index.rst, docs/how-to/source-handler.rst, docs/how-to/source-handler/rsync_parts.yaml, docs/how-to/source-handler/rsync_source.py, tests/integration/sources/test_registered_source.py, tests/unit/sources/test_errors.py, tests/unit/sources/test_git_source.py, tests/unit/sources/test_local_source.py, tests/unit/sources/test_sevenzip_source.py, tests/unit/sources/test_snap_source.py, tests/unit/sources/test_sources.py, tests/unit/sources/test_zip_source.py
This provides a pair of functions (sources.register, sources.unregister) for registering and unregistering source types. This differs slightly from plugin registration:
- All current sources are considered mandatory, meaning they cannot be replaced or unregistered by the application.
- Mandatory sources can be changed at a major release.
-----
Fixes #915, CRAFT-3734
=> feat: add an API for registering source types

docs/common/craft-parts/reference/plugins/uv_plugin.rst
-----
Needed by https://github.com/canonical/charmcraft/pull/2050
=> docs: update docs with extra ref anchors

craft_parts/plugins/base.py, craft_parts/plugins/python_plugin.py, tests/integration/plugins/test_npm.py, tests/integration/plugins/test_python.py, tests/unit/plugins/test_python_plugin.py, tests/unit/plugins/testfiles/python/install/bin/doit, tests/unit/plugins/testfiles/python/install/lib/python/site-packages/fakeee-1.2.3-deb_ian.dist-info/LICENSE.txt, tests/unit/plugins/testfiles/python/install/lib/python/site-packages/fakeee-1.2.3-deb_ian.dist-info/METADATA, tests/unit/plugins/testfiles/python/install/lib/python/site-packages/fakeee-1.2.3-deb_ian.dist-info/RECORD, tests/unit/plugins/testfiles/python/install/lib/python/site-packages/fakeee/a_file.py, tests/unit/plugins/testfiles/python/install/lib/python/site-packages/fakeee/things/nothing.py, tests/unit/plugins/testfiles/python/install/lib/python/site-packages/fakeee/things/stuff.py
-----
Implement origin package -> file mapping for the python plugin, to be used in xattr tagging.
(CRAFT-3758)
=> feat: python plugin file listing

docs/reference/changelog.rst
-----
1.25.3 brought dependency updates and CI fixes that are already exist in `main` or are not relevant, so there are no changes here.
=> chore(merge): 1.25.3 into main

craft_parts/plugins/poetry_plugin.py, docs/common/craft-parts/reference/plugins/poetry_plugin.rst
--with is required for optional and non-optional dependencies
see https://github.com/python-poetry/poetry-plugin-export/pull/212 and https://github.com/python-poetry/poetry-plugin-export/issues/299
=> docs: Fix poetry-with description

docs/common/craft-parts/reference/plugins/poetry_plugin.rst
This allows applications that have their own custom poetry reference to include all the default links by adding the following to the bottom of their poetry plugin reference:
```
.. include:: /common/craft-parts/reference/plugins/poetry_plugin.rst
:start-after: .. _craft_parts_poetry_links:
```
-----
=> fix(docs): include poetry links as a target

craft_parts/executor/part_handler.py, craft_parts/packages/platform.py, craft_parts/plugins/base.py, craft_parts/plugins/npm_plugin.py, craft_parts/plugins/python_plugin.py, craft_parts/xattrs.py, docs/common/craft-parts/craft-parts.wordlist.txt, pyproject.toml, tests/integration/plugins/test_npm.py, tests/integration/plugins/test_python.py, tests/unit/executor/test_part_handler.py, tests/unit/packages/test_normalize.py, tests/unit/plugins/test_npm_plugin.py, tests/unit/plugins/test_python_plugin.py
-----
Implement flow code, defined by https://docs.google.com/document/d/1wVtAYJouIXotd8iCZMZ_1VpmGpN0yoLfKcxeOBIgotw/edit?tab=t.0
(CRAFT-3741)
=> feat: flow for plugin package file mapping and xattr tagging

docs/reference/changelog.rst
* Change craftctl communication mechanism to unix sockets to consolidate
the ctl server and output stream processing selector loops.
* Get the error output from step scriptlet execution and surface it when
raising ScriptletRunError.
-----
=> Release 2.3.0

craft_parts/plugins/go_use_plugin.py, docs/reference/changelog.rst, tests/unit/plugins/test_go_use_plugin.py
It's possible, and somewhat common, for a go module to be defined inside a repo's subdir; in this case we can define source-subdir, but the go-use plugin needs to use this - otherwise the repo root gets used.
Fixes #978
-----
=> fix: use source-subdir in go-use plugin

craft_parts/packages/normalize.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst, tests/unit/packages/test_normalize.py
The ${pcfiledir} tag allows to make .pc files relocatables, by being replaced with the path where the .pc file is stored. In these cases, the "prefix=" entry must be left as-is, to ensure that it continues to work as expected.
It is complemented by https://github.com/canonical/snapcraft/pull/5157
Fix https://github.com/canonical/snapcraft/issues/5158
-----
=> fix: Honor the ${pcfiledir} entries in pkgconfig

craft_parts/plugins/uv_plugin.py, craft_parts/sources/__init__.py, docs/conf.py, docs/reference/changelog.rst, tests/integration/plugins/test_uv.py, tests/unit/plugins/test_java_plugin.py
-----
Cherry-picks #1003 to `hotfix/2.3` for Snapcraft 8.6.1. 
The only new change is the commit that ignores `crates.io`.
=> docs(changelog): add 2.3.1 entry

docs/conf.py, docs/reference/changelog.rst
-----
This hotfix cherry-picked existing changes on `main` except for the changelog and an ignore for crate.io.
=> chore(merge): 2.3.1 into main

craft_parts/plugins/jlink_plugin.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst, tests/integration/plugins/test_jlink.py
-----
Fixes: https://github.com/canonical/craft-parts/issues/1013#issue-2842179681
=> fix: CPATH persistence

craft_parts/errors.py, craft_parts/executor/step_handler.py, craft_parts/plugins/base.py, docs/reference/changelog.rst, pyproject.toml, tests/integration/executor/test_errors.py, tests/integration/plugins/test_poetry.py, tests/integration/plugins/test_python.py, tests/unit/plugins/test_base.py, tests/unit/plugins/test_base_python.py, tests/unit/utils/test_process.py
In case of Python plugin build errors, print error messages to stderr
instead of stdout so they can be captured and properly displayed to the
user. Don't start printing from the last script execution trace line because
messages printed to stderr appear before the traced `exit` line.
Fixes #1000 
-----
=> fix(errors): reformat plugin build error output

docs/common/craft-parts/reference/plugins/poetry_plugin.rst, docs/common/craft-parts/reference/plugins/uv_plugin.rst
Prevents some issues with the docs in downstream apps. See commit messages for details.
---
-----
=> docs: prevent transclusion issues

craft_parts/sources/errors.py, craft_parts/sources/git_source.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst, tests/integration/sources/test_git_source.py, tests/unit/sources/test_errors.py, tests/unit/sources/test_git_source.py
-----
Previously, `source-commit` could only accept full length (40 character) hashes. Now, `source-commit` can accept short hashes.
I recommend reviewing by commit because the first commit is a refactor that moves a bunch of tests.
Fixes #1008
(CRAFT-4127)
=> feat: allow short commit hashes

craft_parts/plugins/uv_plugin.py, craft_parts/sources/__init__.py, docs/conf.py, docs/reference/changelog.rst, pyproject.toml, tests/integration/plugins/test_uv.py
-----
Cherry-picks #1003 onto `hotfix/2.4` to fix a regression in Snapcraft.
=> fix: don't require a specific python interpreter for uv (#1003)

craft_parts/plugins/jlink_plugin.py, docs/reference/changelog.rst, tests/unit/plugins/test_jlink_plugin.py
-----
Note: The actual fix was quoting the "*.jar" in the find command, which was being expanded by bash instead of find. It was moved into a function in the name of testing.
Closes #1027
CRAFT-4266.
=> fix(jlink): find all jar files in default behavior

craft_parts/utils/process.py, docs/reference/changelog.rst
Run subprocess output one last time before exiting the combined output
processing loop.
Fix #1025
-----
=> fix(util/process): collect complete output from subprocess

docs/requirements.txt, uv.lock
Address CVE-2025-27516: Jinja2 vulnerable to sandbox breakout through
attr filter selecting format method.
See https://osv.dev/vulnerability/GHSA-cpwx-vrp4-4pq7 for details.
-----
=> build(deps): update jinja2 to 3.1.6

pyproject.toml
-----
Ruff 0.10 made the [rule for module shadowing](https://docs.astral.sh/ruff/settings/#lint_flake8-builtins_strict-checking) less strict by default.  My preference is to keep the same level of strictness.
See the "failure" [here](https://github.com/canonical/craft-parts/actions/runs/13917827360/job/38944036599?pr=1044), where a `noqa` becomes superfluous.
=> style: enforce strict checking for shadowing

craft_parts/overlays/chroot.py
-----
This PR adds a directory to the set of paths mounted when executing `craftctl chroot ...`. This change is necessary for noble build-bases to verify archive signatures during the hidden apt-upgrade step.
=> fix: add keyrings to standard chroot mount

docs/common/craft-parts/reference/part_properties.rst
-----
This PR modifies the types from `part-properties` docs page to be actual variable types.
---
See [built-docs](https://canonical-craft-parts--1055.com.readthedocs.build/en/1055/)
=> docs: modify types to be actual variable types

.github/workflows/tests.yaml
-----
Drops focal from CI now that is no longer available as a github runner (https://github.com/actions/runner-images/issues/11101).
=> ci: drop focal tests

.readthedocs.yml, docs/reference/changelog.rst
This fixes a regression. Do we want a changelog entry for it?
---
-----
=> docs(build): switch to extensionless URLs

craft_parts/errors.py, tests/integration/executor/test_errors.py, tests/unit/test_errors.py
-----
I couldn't find any applications consuming craft-parts that still use the `.html` extension on RTD, so I believe this can be updated safely. If I'm overlooking anything, please let me know.
=> fix: remove .html extension from doc slug

docs/reference/changelog.rst
-----
There were 3 pending releases, 2.8.1, 2.9.0, and 2.10.0.  None of them have been released and they were conflated by multiple PRs updating the changelog differently.
This PR combines all the unreleased changes into 2.9.0.
=> docs(changelog): finalize 2.9.0

craft_parts/packages/platform.py, craft_parts/plugins/uv_plugin.py, docs/reference/changelog.rst, docs/requirements.txt
-----
This backports #1086 to the 2.4 branch for Charmcraft 3.4
=> Fix and changelog for 2.4.4

craft_parts/packages/platform.py, craft_parts/plugins/uv_plugin.py, docs/reference/changelog.rst, docs/requirements.txt
-----
This backports the UV 0.7 fix to the 2.7 branch for Snapcraft
=> Backport uv fix to 2.7

craft_parts/plugins/go_plugin.py, craft_parts/plugins/go_use_plugin.py, tests/integration/plugins/test_go.py, tests/integration/plugins/test_go_use.py, tests/unit/plugins/test_go_plugin.py, tests/unit/plugins/test_go_use_plugin.py
-----
This rearranges the way the `go` plugin and the `go-use` plugin work together. The `go` plugin now checks its dependencies and sets up a workspace if relevant, allowing for a mix of online and offline builds in a single `parts.yaml`. The `go-use` plugin simply creates what's roughly equivalent to a Debian vendor repository.
CRAFT-4530
=> feat(go-use): make the go-use plugin use backstage

docs/reference/changelog.rst
-----
Adds reference tags to each release note.
Previously, links to releases would have reference tags like `#id1`, `#id2`, and so on.  This was bad because the tags would point to a different release each time a new release was added.
This also adds a template to make future releases more consistent.
=> docs(changelog): add template and refs to all releases

.github/workflows/tests.yaml
-----
`matrix.platform` is not defined (anymore?), so use `matrix.os`.
=> ci: reference the OS to build the tox tests result filename

craft_parts/utils/maven/common.py, docs/reference/changelog.rst, tests/integration/plugins/test_maven_use.py, tests/integration/plugins/test_maven_use/java-main-part/pom.xml, tests/unit/utils/test_maven_utils.py
-----
The maven-use plugin will always overwrite the version number of a dependency with whatever is available (unless, of course, what's available is already being used). In the case that a version number isn't specified at all, instead of raising an error, the plugin should just simply write in a version that is available.
CRAFT-4601
=> fix(maven-use): always set version

craft_parts/utils/maven/_xml.py, craft_parts/utils/maven/common.py, docs/reference/changelog.rst, tests/unit/utils/test_maven_utils.py
-----
In projects that already have a `<distributionManagement>` tag in their `pom.xml` file, maven-use would append a second one instead of modifying the existing one, which caused a build error from Maven. This PR changes the behavior to always overwrite the existing tag, if present. This is acceptable because the tag's purpose is configuring remote indexes to upload builds of the project, but the only place that the maven-use plugin should deploy is to the local backstage directory.
CRAFT-4603
=> fix(maven-use): don't duplicate distributionManagement tags

craft_parts/__init__.py, craft_parts/infos.py, docs/reference/changelog.rst
-----
Avoid these imports/exports shave ~150-200ms of importing craft-parts. Moreover these are not used outside of craft-parts.
This can be tested by comparing profiles generated with `python3 -X importtime -mcraft_parts --help 2> craft-parts.prof`
=> perf: Do not import filesystem_mounts object in __init__

docs/reference/changelog.rst
The feature's PR took long enough that releases were made between PR creation and merging, so the changelog entry ended up for a release that had already happened.
-----
=> docs: fix jlink entry in changelog

craft_parts/parts.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst
-----
Remove Craft Parts links from field docstrings
These links should be replaced downstream as internal references to ensure that they are properly versioned and resistant to breakage.
=> docs: remove Craft Parts links from docstrings

craft_parts/errors.py, craft_parts/executor/collisions.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst, tests/conftest.py, tests/integration/executor/test_collisions.py, tests/integration/lifecycle/test_overlay.py, tests/unit/executor/test_collisions.py
This commit enhances the collision detection in the Stage step to also take into account contents coming from the overlay. The standard collision detection was done by comparing the contents of the install directories for the existing parts - this behavior persists, but now we *also* take into account the contents of each overlay-enabled part's layer directory, considering the layer stack to only report collisions between items that would *actually* be staged.
To validate the implementation, this commit adds extensive integration tests for scenarios that *must* collide, plus scenarios that *must not*.
-----
=> fix(overlay): detect conflicts between overlay and install

CONTRIBUTING.md
This one slipped through the cracks during the planning for this pulse.
[Updated `CONTRIBUTING.md`](https://github.com/canonical/craft-parts/blob/work/update-contributing-guide/CONTRIBUTING.md)
=> docs: align `CONTRIBUTING.md` with template

craft_parts/__init__.py, craft_parts/actions.py, craft_parts/executor/executor.py, craft_parts/infos.py, craft_parts/lifecycle_manager.py, craft_parts/sequencer.py, craft_parts/state_manager/build_state.py, craft_parts/state_manager/overlay_state.py, craft_parts/state_manager/prime_state.py, craft_parts/state_manager/pull_state.py, craft_parts/state_manager/stage_state.py, craft_parts/state_manager/state_manager.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst, tests/integration/lifecycle/test_craftctl.py, tests/integration/lifecycle/test_plugin_changesets.py, tests/unit/state_manager/conftest.py, tests/unit/test_actions.py, tests/unit/test_infos.py
-----
Uses the new `ProjectVarInfo` class to manage project variables. This enables setting nested project variables.  For example, `craftctl set var.subvar=foo` sets the nested project variable `var.subvar` to `foo`.
Used downstream in https://github.com/canonical/craft-application/pull/872
(SNAPCRAFT-1052)
=> feat: support nested project variables

craft_parts/executor/part_handler.py, craft_parts/lifecycle_manager.py, craft_parts/parts.py, craft_parts/utils/partition_utils.py, docs/common/craft-parts/craft-parts.wordlist.txt, docs/reference/changelog.rst, tests/conftest.py, tests/integration/lifecycle/test_organize_to_overlay.py, tests/unit/features/overlay_partitions/test_executor_organize.py, tests/unit/features/overlay_partitions/test_parts.py, tests/unit/features/partitions/test_parts.py, tests/unit/test_dirs.py, tests/unit/test_parts.py
Establish the `(overlay)` target to file organization. When a part
organizes to `(overlay)`, files are moved from the part's build directory
to the top of the mounted overlay stack.
-----
=> feat: allow parts to organize to overlay

craft_parts/filesystem_mounts.py, docs/reference/changelog.rst, tests/unit/test_filesystem_mounts.py
=> feat: Enforce filesystem mounts to be ordered in increasing mount nesting

Makefile
Workaround for https://github.com/actions/runner-images/issues/13138
---
=> ci: remove unwanted Java 25 from GitHub hosted runners
