canonical/craft-parts

- Makefile
- craft_parts/dirs.py
- craft_parts/errors.py
- craft_parts/parts.py
- craft_parts/steps.py
- docs/exceptions.rst
- docs/index.rst
- docs/parts_steps.rst
- tests/conftest.py
- tests/unit/test_dirs.py
- tests/unit/test_errors.py
- tests/unit/test_parts.py
- tests/unit/test_steps.py
Parts and steps are the basic data types craft-parts will work with.
Together, they define the lifecycle of a project (i.e. how to process
each step of each part in order to obtain the final primed result).
-----
> Add parts and steps definitions

- craft_parts/plugins/dump_plugin.py
- tests/integration/plugins/test_dump.py
- tests/unit/plugins/test_dump_plugin.py
The dump plugin copies content from the part source.
-----
> plugins: add the dump plugin

- craft_parts/__init__.py
- docs/conf.py
- docs/infos.rst
- docs/requirements.txt
- requirements-dev.txt
Add a docs-specific list of requirements and fix sphinx doc generation
for pydantic classes.
-----
> docs: fix document generation

- .readthedocs.yml
> docs: add readthedocs yaml file

- craft_parts/errors.py
- tests/unit/test_errors.py
Implement the error classes used during step handling.
-----
> executor: add step handler errors

- craft_parts/executor/part_handler.py
- craft_parts/executor/step_handler.py
- craft_parts/infos.py
- craft_parts/lifecycle_manager.py
- tests/unit/executor/test_part_handler.py
- tests/unit/executor/test_step_handler.py
Handle part run actions by fetching and unpacking packages, calling the
appropriate step handler, and generating the step state data.
-----
> executor: add part handler (1/2)

- craft_parts/plugins/plugins.py
- craft_parts/plugins/python_plugin.py
- tests/integration/plugins/test_python.py
- tests/unit/plugins/test_plugins.py
- tests/unit/plugins/test_python_plugin.py
The python plugin ported from snapcraft.
-----
> plugins: add python plugin

- craft_parts/executor/part_handler.py
- craft_parts/sources/local_source.py
- craft_parts/state_manager/states.py
- tests/unit/executor/test_part_handler.py
- tests/unit/state_manager/test_states.py
Handle `ActionType.RERUN` and `ActionType.UPDATE` actions.
-----
> executor: add part handler (2/2)

- craft_parts/executor/__init__.py
- craft_parts/executor/executor.py
- craft_parts/executor/part_handler.py
- craft_parts/lifecycle_manager.py
- craft_parts/parts.py
- craft_parts/utils/os_utils.py
- tests/integration/executor/test_steps.py
- tests/integration/lifecycle/test_lifecycle.py
- tests/unit/executor/test_executor.py
- tests/unit/executor/test_part_handler.py
- tests/unit/test_parts.py
Add the calls to execute actions using the lifecycle manager.
Additional tests will be added in separate PRs.
-----
> executor: add executor class and integrate with lifecycle manager (CRAFT-31)

- Makefile
- craft_parts/executor/collisions.py
- craft_parts/sources/snap_source.py
- craft_parts/sources/tar_source.py
- craft_parts/state_manager/states.py
- craft_parts/state_manager/step_state.py
- craft_parts/utils/__init__.py
- tests/unit/executor/test_part_handler.py
Address linter warnings raised by new versions of mypy and pylint (or
silence some of them in tests).
-----
> many: address new linter warnings (CRAFT-364)

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/conf.py
- setup.cfg
- setup.py
Fix bumpversion configuration and bump version to 1.0.0.
-----
> release: bump version to 1.0.0 (CRAFT-439)

- craft_parts/executor/part_handler.py
- craft_parts/state_manager/state_manager.py
- craft_parts/state_manager/states.py
- craft_parts/state_manager/step_state.py
- tests/unit/state_manager/test_states.py
- tests/unit/state_manager/test_step_state.py
Refactor step state and add a migration state superclass to be used
when migrating overlay files.
-----
> states: refactor step state class, add migration state (CRAFT-471)

- tests/unit/plugins/test_base.py
Fix assignment of instance to plugin properties class variable.
-----
> plugins: fix plugin properties test (CRAFT-483)

- requirements-bionic.txt
- requirements-focal.txt
Python-apt 2.0.0ubuntu0.20.04.5 was replaced by 2.0.0ubuntu0.20.04.6,
update dependencies accordingly.
-----
> packaging: update python-apt version (CRAFT-510)

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/plugins/__init__.py
- craft_parts/sources/base.py
- craft_parts/sources/errors.py
- craft_parts/sources/git_source.py
- craft_parts/sources/sources.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- tests/unit/sources/test_errors.py
- tests/unit/sources/test_git_source.py
Changelog
========
* Declare additional public API names
* Add git source handler
-----
> release: bump version to 1.0.4

- README.md
Complement the README file with directions on how to run tests, freeze
requirements and generate documentation locally. General commit message
guidelines also added.
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
> docs: add additional info to readme

- craft_parts/plugins/dotnet_plugin.py
- craft_parts/plugins/plugins.py
- tests/integration/plugins/test_dotnet.py
- tests/unit/plugins/test_dotnet_plugin.py
> plugins: add dotnet plugin (CRAFT-612)

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- Pin pydantic and pydantic-yaml dependency versions
> release: craft-parts 1.1.1

- pyproject.toml
> linters: re-enable pylint fixme info

- craft_parts/parts.py
- craft_parts/sources/base.py
- craft_parts/sources/git_source.py
- craft_parts/sources/sources.py
- craft_parts/sources/tar_source.py
- craft_parts/state_manager/pull_state.py
- tests/integration/sequencer/test_sequencer.py
- tests/unit/sources/test_base.py
- tests/unit/sources/test_git_source.py
- tests/unit/state_manager/test_pull_state.py
- tests/unit/test_parts.py
-----
Duplicate of https://github.com/snapcore/snapcraft/pull/3629, but applied to `craft-parts`.
> sources: make submodule fetching configurable

- setup.py
This is a follow-up to PR #173 (CRAFT-743)
-----
> setup: update classifiers

- craft_parts/packages/deb.py
> packages: log AptCache import error

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Make git submodules fetching configurable
* Fix source type specification
* Fix testing in Python 3.10
* Address issues found by linters
-----
> Release 1.2.0

- .github/workflows/tests.yaml
- craft_parts/executor/part_handler.py
- craft_parts/plugins/meson_plugin.py
- craft_parts/plugins/plugins.py
- tests/integration/plugins/test_meson.py
- tests/unit/executor/test_part_handler.py
- tests/unit/plugins/test_meson_plugin.py
Also fix out of source building logic.
-----
CRAFT-863
> plugins: add meson plugin

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add meson plugin
* Adjustments in git source tests
-----
> Release 1.3.0

- craft_parts/executor/executor.py
- craft_parts/executor/part_handler.py
- craft_parts/executor/step_handler.py
- craft_parts/main.py
- tests/integration/executor/test_callbacks.py
- tests/integration/plugins/test_application_plugin.py
- tests/integration/test_main.py
- tests/unit/executor/test_executor.py
- tests/unit/executor/test_part_handler.py
- tests/unit/executor/test_step_handler.py
Output to user-specified stdout and stderr when executing a step. This
allows better control of application verbosity levels.
-----
CRAFT-832
> executor: output to user-specified streams

- .github/workflows/tests.yaml
- craft_parts/plugins/cmake_plugin.py
- craft_parts/plugins/plugins.py
- tests/integration/plugins/test_cmake.py
- tests/unit/plugins/test_cmake_plugin.py
- tests/unit/plugins/test_plugins.py
-----
Port `cmake` plugin to `craft-parts`.
(CRAFT-906)
> plugins: cmake

- docs/craftctl.rst
- docs/index.rst
- docs/parts_steps.rst
Update documentation to include information about valid craftctl
commands and how to declare and retrieve project variables.
-----
CRAFT-939
> docs: document craftctl and step environment

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add cmake plugin
* Mount overlays using fuse-overlayfs
* Send execution output to user-specified streams
* Update craftctl commands
* Update step execution environment variables
-----
CRAFT-937
> Release 1.4.0

- craft_parts/executor/step_handler.py
- tests/integration/lifecycle/test_craftctl.py
Errors arising from usage of the control API should be sent back
to the client instead of triggering a server-side exception.
-----
> craftctl: fix client error handling

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/executor/step_handler.py
- craft_parts/state_manager/state_manager.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- tests/integration/lifecycle/test_craftctl.py
- tests/unit/state_manager/test_state_manager.py
* Fix craftctl error handling
* Fix long recursions in dirty step verification
-----
> Release 1.4.2

- tests/conftest.py
- tests/unit/plugins/test_dotnet_plugin.py
- tests/unit/plugins/test_go_plugin.py
- tests/unit/plugins/test_meson_plugin.py
-----
Replace redundant fixtures with a fixture factory.
> tests: refactor plugin dependency tests

- Makefile
- craft_parts/plugins/plugins.py
- craft_parts/plugins/rust_plugin.py
- tests/integration/plugins/test_rust.py
- tests/unit/plugins/test_plugins.py
- tests/unit/plugins/test_rust_plugin.py
-----
Port the `rust` plugin from [`snapcraft`](https://github.com/snapcore/snapcraft/blob/main/snapcraft/plugins/v2/rust.py) to `craft-parts`.
Will land this PR after https://github.com/canonical/craft-parts/pull/199.
CRAFT-955
> plugins: rust

- craft_parts/plugins/npm_plugin.py
- craft_parts/plugins/plugins.py
- tests/integration/plugins/test_npm.py
- tests/unit/plugins/test_npm_plugin.py
- tests/unit/plugins/test_plugins.py
-----
Port the `npm` plugin from [`snapcraft`](https://github.com/snapcore/snapcraft/blob/main/snapcraft/plugins/v2/npm.py) to `craft-parts`.
CRAFT-957
> plugins: npm

- craft_parts/__init__.py
- craft_parts/plugins/__init__.py
Also remove the noqa tag for unused imports.
-----
> plugins: export missing symbols

- craft_parts/executor/environment.py
- craft_parts/infos.py
- craft_parts/lifecycle_manager.py
- tests/unit/executor/test_environment.py
> part info: support and expose the project name

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add rust plugin
* Add npm plugin
* Add project name argument to LifecycleManager and set `CRAFT_PROJECT_NAME`
* Export symbols needed by application-defined plugins
* Refactor plugin environment validation
-----
> Release 1.5.0

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add zip source handler
* Clean up source provisioning
* Fix project variable setting for skipped parts
-----
> Release 1.6.0

- craft_parts/packages/normalize.py
- docs/changelog.rst
- tests/unit/packages/test_normalize.py
* Fix stage package symlink normalization
-----
> Release 1.6.1

- craft_parts/overlays/overlay_manager.py
- craft_parts/packages/base.py
- craft_parts/packages/deb.py
- tests/unit/overlays/test_overlay_manager.py
- tests/unit/packages/test_deb.py
> packages: update the cache before creating list

- craft_parts/packages/deb.py
Bring forward the same behavior as for core20.
-----
> packages: package filter for core22

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add support for application-defined environment variables
* Add package filter for core22
* Refresh packages list before installing packages
* Expand global variables in parts definition
* Adjust prologue/epilogue callback parameters
* Make plugin options available in plugin environment validator
* Fix readthedocs documentation generation
-----
> Release 1.7.0

- craft_parts/packages/snaps.py
> packages: add debug messages for snap install

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/packages/snaps.py
- craft_parts/plugins/dotnet_plugin.py
- craft_parts/plugins/go_plugin.py
- craft_parts/plugins/meson_plugin.py
- craft_parts/plugins/npm_plugin.py
- craft_parts/plugins/rust_plugin.py
- craft_parts/plugins/validator.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- tests/fake_snap_command.py
- tests/unit/plugins/test_dotnet_plugin.py
- tests/unit/plugins/test_go_plugin.py
- tests/unit/plugins/test_meson_plugin.py
- tests/unit/plugins/test_npm_plugin.py
- tests/unit/plugins/test_rust_plugin.py
* Fix stdout leak during snap package installation
* Fix plugin validation dependencies
-----
> Release 1.7.1

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add list of primed stage packages to prime state
* Add lifecycle manager methods to obtain pull state assets and the list of primed stage packages
-----
> Release 1.8.0

- craft_parts/packages/deb.py
- tests/unit/packages/test_deb.py
Collect installed package versions after the installation.
This allows us to collect the real version whilst avoiding a bug
in apt where it would downgrade or remove a package in cases where
the pinned version cannot be satisfied.
-----
This would no longer auto mark packages (not useful anymore and --destructive-mode is destructive).
Only the requested packages are passed on to apt install with a best effort of collecting what dependencies would be installed or how virtual packages would be resolved to construct the most backwards compatible result at the end of the process.
CRAFT-1187
> packages: install unpinned

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Prevent wildcard symbol conflict in stage and prime filters
* Apt installer changed to collect installed package versions after the
installation
> Release 1.9.0

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add plugin class method to check for out of source builds
* Normalize file copy functions signatures
* Fix pkgconfig prefix in staged snaps
-----
> Release 1.10.0

- craft_parts/sources/git_source.py
- tests/unit/sources/test_git_source.py
-----
Local git sources are reformatted as `file:///absolute/path/to/local/source`
This is done because `git clone --depth=1 path/to/local/source` is invalid.
LP: #[1979529](https://bugs.launchpad.net/snapcraft/+bug/1979529)
(CRAFT-1153)
> sources: format local git paths as file://<path>

- craft_parts/plugins/__init__.py
- craft_parts/plugins/plugins.py
- tests/unit/plugins/test_plugins.py
> plugins: add method to list registered plugins

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add API call to list registered plugins
> Release 1.11.0

- craft_parts/lifecycle_manager.py
Fix list sorting after removing debug instrumentation.
-----
> lifecycle_manager: minor primed packages sort refactoring

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Set install prefix in the cmake plugin
* Fix prefix path in the cmake plugin
> Release 1.12.0

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/plugins/cmake_plugin.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- tests/integration/plugins/test_cmake.py
- tests/unit/plugins/test_cmake_plugin.py
- Revert changes to install prefix in cmake plugin to prevent
stable base incompatibility
-----
> Release 1.12.1

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge the v1.12 branch back into main.
-----
> merge: v1.12

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add go generate support to go plugin
* Add support for deb sources
* Add source download request timeout
* Remove unnecessary overlay whiteout files
-----
> Release 1.13.0

- craft_parts/parts.py
- tests/unit/test_parts.py
The slices are defined in the regular "stage-packages" by virtue of the fact that .deb package names *cannot* have underscores while chisel slices *must always* have an underscore to distinguish between package name and the specific slice.
-----
(CRAFT-1329)
> spec: add "stage-slices" for chisel slices

- tests/unit/packages/test_normalize.py
> lint: remove leftover pylint directive

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add support to chisel slices
* Add ``go-generate`` property to the go plugin
-----
> Release 1.15.0

- craft_parts/parts.py
- craft_parts/permissions.py
- tests/unit/test_parts.py
- tests/unit/test_permissions.py
Add the base `Permissions` model with basic API. No actual integration into the lifecycle yet (that comes next).
-----
> parts: add Permissions model

- craft_parts/plugins/nil_plugin.py
Update nil plugin documentation with useful information.
Co-authored-by: Robert P. J. Day <robert.day@canonical.com>
-----
> plugins: improve nil plugin docstring

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add file permission setting
* Take permissions into account when checking file collisions
* Only refresh overlay packages if necessary
* Generate separate environment setup file
* Make changed file list available to plugins
-----
> Release 1.16.0

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Fix go plugin mod download in jammy
* Remove hardcoded ubuntu version in chisel call
* Add plain file source handler
* Pass build attributes and state to post-step callback
-----
> Release 1.17.0

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Backport fix to allow plus symbol in git url scheme
-----
> Release 1.15.2

- craft_parts/plugins/dotnet_plugin.py
- [Y] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
Hopefully doesn't need much explanation.
> plugins: Correct docstring in Dotnet plugin

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/conf.py
- docs/reference/changelog.rst
- setup.py
* Add SCons plugin
* Add Ant plugin
* Add Maven plugin
* Fix lifecycle work directory cleaning
* Make stage package tracking optional
* Improve chisel error handling
* Improve missing local source error message
* Documentation fixes and updates
> Release 1.18.0

- craft_parts/executor/part_handler.py
- craft_parts/executor/step_handler.py
- craft_parts/overlays/overlays.py
- craft_parts/packages/base.py
- craft_parts/packages/deb.py
- craft_parts/packages/snaps.py
- craft_parts/plugins/npm_plugin.py
- craft_parts/sources/local_source.py
- pyproject.toml
- setup.py
- tests/integration/lifecycle/test_stage_snaps.py
- tests/integration/sources/test_deb.py
- tests/unit/executor/test_organize.py
> chore(lint): update linters and fix linting issues with new rules

- craft_parts/utils/os_utils.py
- tests/unit/utils/test_os_utils.py
> utils: remove Ubuntu-specific code from OsRelease

- craft_parts/executor/step_handler.py
- pyproject.toml
- setup.py
> lint: strictly set the linter versions for the v1.15 branch

- setup.py
> lint: freeze mypy version until we can address the changes in 1.0

- craft_parts/plugins/npm_plugin.py
- tests/unit/plugins/test_npm_plugin.py
The setting is not longer supported and it seems like it is no longer needed.
-----
> node plugin: remove unsafe perms

- README.md
> readme: update readthedocs link

- .github/workflows/tests.yaml
- tests/integration/plugins/test_dotnet.py
> tests: fix dotnet integration tests

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/plugins/python_plugin.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- tests/integration/plugins/test_python.py
- tests/integration/plugins/test_python/mytest/__init__.py
- tests/integration/plugins/test_python/setup.py
- tests/unit/plugins/test_python_plugin.py
Merge v1.18.3 back into main.
-----
> Merge 1.18.3

- craft_parts/parts.py
> parts.py: a couple of minor grammatical fixups, no functional change

- craft_parts/actions.py
- craft_parts/ctl.py
- craft_parts/errors.py
- craft_parts/infos.py
- craft_parts/main.py
> craft_parts py files: minor typo/grammar/capitalization fixes

- craft_parts/steps.py
- tests/conftest.py
- tests/unit/executor/test_executor.py
- tests/unit/executor/test_part_handler.py
- tests/unit/features/test_overlay_steps.py
- tests/unit/overlays/__init__.py
- tests/unit/state_manager/test_state_manager.py
- tests/unit/test_sequencer.py
When the overlay feature is disabled, the lists of next and previous steps for any given step must not list the overlay step.
-----
> steps: handle overlay feature in step lists

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Initial support for offline plugins
* Initial support for yum and CentOS
* Introduce feature selection, make overlay support optional
* Check if plugin-specific properties are dirty when computing lifecycle actions
* Add source handler for rpm packages
* Ignore unreadable files in /etc/apt
* Documentation updates
* OsRelease code cleanup
-----
> Release 1.19.0

- docs/explanation/parts.rst
-----
Fixes syntax issues in an earlier commit.
> docs: fix list syntax

- tests/unit/executor/test_organize.py
> tests: cast type expectation for organize assertions

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Allow git+ssh in git source type
* Loosen pydantic dependency
-----
> Release 1.19.1

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.19.1 into main.
-----
> Merge 1.19.1

- craft_parts/packages/deb.py
- tests/unit/packages/test_deb.py
Port of https://github.com/snapcore/snapcraft/pull/4026.
-----
> deb: pass set of packages to unmark

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Fix ignored files exclusion in local source 
-----
> Release 1.19.2

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.19.2 back into main.
-----
> Merge 1.19.2

- docs/index.rst
docs: move the page closer to the standard template for documentation
-----
> docs: update package description in  index.rst

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Fix plugin properties state in planning phase
> Release 1.19.3

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/sequencer.py
- craft_parts/state_manager/reports.py
- craft_parts/state_manager/step_state.py
- docs/changelog.rst
- docs/conf.py
- setup.py
- tests/unit/test_sequencer.py
Merge hotfix/1.19.3 back into main.
-----
> Merge 1.19.3

- .github/renovate.json5
> tools: configure renovate

- setup.py
> deps: change python-apt dependencies to launchpad

- docs/explanation/index.rst
> docs: fix title markup

- craft_parts/permissions.py
- craft_parts/plugins/maven_plugin.py
- craft_parts/plugins/scons_plugin.py
- craft_parts/utils/deb_utils.py
- craft_parts/utils/os_utils.py
- docs/reference/actions.rst
- docs/reference/exceptions.rst
- docs/reference/infos.rst
- docs/reference/lifecycle_manager.rst
> docs: fix apidoc warnings

- setup.py
-----
I was over-optimistic about how easy this would be for applications :-)
> deps: rollback hard dependency link for python-apt

- .github/workflows/tests.yaml
> ci: freeze build and lint versions for 1.19

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Backport support for pyproject.toml projects from 1.20.0
* Backport pull and build steps subdir fix from 1.20.0
> Release 1.19.4

- docs/changelog.rst
Merge hotfix/1.19.4 back into main.
> Merge 1.19.4

- docs/changelog.rst
Merge hotfix/1.19.5 back into main.
-----
> Merge 1.19.5

- craft_parts/executor/filesets.py
- craft_parts/executor/organize.py
- craft_parts/infos.py
- craft_parts/overlays/overlay_manager.py
- craft_parts/packages/deb.py
- craft_parts/packages/snaps.py
- craft_parts/sources/base.py
- craft_parts/utils/os_utils.py
- craft_parts/utils/url_utils.py
- tests/unit/utils/test_url_utils.py
The codebase contained a number of outdated, unnecessary, or otherwise
impractical to implement TODOs that would most likely never be done.
Remove those, and keep the ones that we will actually work on.
-----
> many: remove todos what won't be done

- docs/explanation/parts.rst
- docs/how-to/index.rst
- docs/how-to/override_build.rst
> docs: add a how-to for overriding builds

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Revert subdir changes in pull and build steps
-----
> Release 1.21.1

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Revert subdir changes in pull and build steps
-----
> Release 1.19.6

- craft_parts/infos.py
-----
https://github.com/canonical/craft-parts/issues/474
> info: convert TODO to bug

- craft_parts/executor/part_handler.py
- tests/unit/executor/test_part_handler.py
- tests/unit/features/overlay/test_executor_part_handler.py
Merge hotfix/1.19.6 back into main.
-----
> Merge 1.19.6

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.21.1 back into main.
-----
> Merge 1.21.1

- craft_parts/infos.py
- tests/unit/test_infos.py
> infos: apply architecture maps if needed

- docs/base/part_properties.rst
- docs/explanation/filesets.rst
- docs/reference/parts_steps.rst
- docs/tutorials/hello-craft-parts.rst
> docs: fixed broken references

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Improve interpreter version detection in the Python plugin
* Fix and improve documentation
* Pin Pydantic to version 1.x
-----
> Release 1.23.0

- setup.py
pydantic-yaml 1.0.0 changes the API a bit and will need some small refactoring, as noted in #499
-----
> deps: freeze pydantic-yaml <1.0.0

- .gitmodules
- .readthedocs.yml
- docs/Makefile
- docs/conf.py
- docs/explanation/filesets.rst
- docs/explanation/parts.rst
-----
Generated documentation here: https://canonical-craft-parts--501.com.readthedocs.build/en/501/
> docs: update Sphinx theme

- setup.py
-----
CI fixed in combination with #512. This is visible in the CI results from #513.
> deps: freeze pydantic version

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Only load project variables in adopting part
-----
> Release 1.19.7

- .readthedocs.yml
> docs: disable pdf in .readthedocs.yml

- setup.py
pydantic-yaml 1.0.0 changes the API a bit and will need some small refactoring.
(cherry picked from commit 5b463227712ac3077a4b78e4e69ca1c93b091832)
-----
> deps: freeze pydantic-yaml <1.0.0 (#498)

- .github/renovate.json5
> ci: fix renovate scheduling

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Only load project variables in adopting part
-----
> Release 1.23.1

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.23.1 back into main.
-----
> Merge 1.23.1

- pyrightconfig.json
- setup.py
- tests/integration/features/partitions/lifecycle/test_lifecycle.py
- tests/integration/features/partitions/plugins/test_plugins.py
> lint: update and freeze pyright

- craft_parts/dirs.py
- craft_parts/lifecycle_manager.py
- craft_parts/utils/partition_utils.py
- tests/integration/sequencer/test_sequencer.py
- tests/unit/features/partitions/test_lifecycle_manager.py
- tests/unit/test_dirs.py
- tests/unit/test_lifecycle_manager.py
- tests/unit/utils/test_partition_utils.py
> partitions: make partitions optional in ProjectDirs

- .github/workflows/tests.yaml
- craft_parts/plugins/autotools_plugin.py
- tests/integration/plugins/test_autotools.py
- tests/unit/plugins/test_autotools_plugin.py
> autotools plugin: support bootstrap parameters

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add support to partitions
* Add lifecycle prologue log messages
* Add build-on/for architecture environment variables
* Add bootstrap parameters to autotools plugin
* Documentation updates
-----
> Release 1.24.0

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.24.1 back into main.
-----
> Merge 1.24.1

- docs/base/rust_plugin.rst
- docs/reference/plugins.rst
- docs/reference/plugins/rust_plugin.rst
-----
This pull request adds the documentation for the Rust plugin that just got merged (as of writing).
> docs: add documentation for Rust plugin

- .github/workflows/tests.yaml
- README.md
- setup.py
> deps: remove python-apt from setup.py

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Remove direct dependency to python-apt tarball
> Release 1.25.1

- README.md
-----
Preview at https://github.com/canonical/craft-parts/blob/docs-badge/README.md
> docs(readme): add readthedocs build badge

- .bumpversion.cfg
- .github/workflows/tests.yaml
- README.md
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.25.1 back into main.
> Merge 1.25.1

- .readthedocs.yml
> chore(deps): update readthedocs environment

- craft_parts/parts.py
- craft_parts/plugins/rust_plugin.py
- pyproject.toml
- setup.py
> chore(deps): update type checkers

- setup.py
> ci: pin pylint version

- craft_parts/parts.py
- craft_parts/plugins/rust_plugin.py
- pyproject.toml
- setup.py
> ci: fix linter issues

- craft_parts/plugins/rust_plugin.py
* Detect and remove compiler plugins from the final Snap package
* Remove the redundant channel override that caused some issues with
type-checking, and it is actually not needed.
-----
> rust_plugin: multiple fixes  (#560)

- craft_parts/executor/environment.py
- tests/integration/executor/test_environment.py
- tests/integration/executor/test_environment_overlay.py
- tests/unit/executor/test_environment.py
- tests/unit/features/overlay/test_executor_environment.py
> fix(environment): sort project variables before replacement

- tests/conftest.py
-----
I caught this when running the tests in Python 3.11. The upstream change was https://github.com/python/cpython/pull/31090
> test: fix mock chroot fixture

- tox.ini
> build: fix tox test environments

- craft_parts/plugins/rust_plugin.py
- setup.py
- tests/unit/plugins/test_rust_plugin.py
-----
This ensures that you don't have to have rust on your system in order to run the rust plugin unit tests
> test: rust plugin unit tests - remove system requirements

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
Merge hotfix/1.25.2 back into main.
-----
> Merge 1.25.2

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Documentation updates
* Build system, requirements and CI updates
* Misc unit test fixes and updates
-----
> Release 1.26.0

- craft_parts/infos.py
- craft_parts/lifecycle_manager.py
- tests/unit/test_lifecycle_manager.py
> feat(info): add base layer data to ProjectInfo

- .github/renovate.json5
> chore(deps): disable renovate on things we can't update

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Fix chisel slice normalization
* Address sphinx warnings
-----
> Release 1.26.1

- .github/renovate.json5
- setup.py
> chore(deps): prevent renovate from updating types-requests

- craft_parts/plugins/base.py
-----
Add a note about a requirement for plugin properties.
From https://github.com/snapcore/snapcraft/pull/4491#discussion_r1425304237
> docs: add note about plugin-specific properties

- craft_parts/plugins/qmake_plugin.py
- tests/unit/overlays/test_overlay_manager.py
- tests/unit/plugins/test_base.py
- tests/unit/plugins/test_qmake_plugin.py
- tests/unit/sources/test_base.py
> test: make tests work in python 3.12+

- craft_parts/executor/filesets.py
- craft_parts/executor/organize.py
> chore: update fileset and organize docstrings

- setup.py
-----
Cherry-pick #628 onto a feature branch
> build(deps): pin overrides!=7.6.0 (#628)

- craft_parts/packages/deb.py
- docs/base/rust_plugin.rst
- setup.py
- tests/integration/features/partitions/lifecycle/test_lifecycle.py
-----
Drive-by: autofix with codespell
> style: update pyright

- .github/workflows/tests.yaml
- craft_parts/executor/part_handler.py
- craft_parts/parts.py
- tests/integration/test_logging.py
Backport fix from 632f0933ef2308ac9eca75b9a74dc274af3320b6.
-----
> fix(parts): set field defaults using default_factory (#629)

- craft_parts/executor/executor.py
- craft_parts/executor/part_handler.py
- tests/integration/features/partitions/lifecycle/test_lifecycle.py
- tests/unit/executor/test_executor.py
- tests/unit/features/overlay/test_executor.py
- tests/unit/features/partitions/executor/test_executor.py
-----
Clean partition directories when the partitions feature is enabled.
Fixes #634 
(CRAFT-2417)
> feat(partitions): clean partition directories

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Fix default setting in aliased part fields
* Fix proxy setting in ant plugin
-----
> Release 1.26.2

- craft_parts/errors.py
- craft_parts/executor/collisions.py
- craft_parts/executor/executor.py
- tests/integration/executor/test_collisions.py
- tests/integration/features/partitions/executor/test_collisions.py
- tests/unit/executor/test_collisions.py
- tests/unit/features/partitions/executor/test_collisions.py
- tests/unit/test_errors.py
-----
Check for collisions where multiple parts try to stage a file with different contents in each partition.
I refactored the existing unit tests and added new integration tests.  I recommend reviewing per-commit.
Fixes #633 
(CRAFT-2416)
> feat(executor): check for stage file collisions in each partition

- tests/integration/features/partitions/lifecycle/test_lifecycle.py
-----
This adds a regression test for #665.  It's marked as an `xfail` since the work is not done.
> test: add test for cleaning duplicate files in multiple partitions

- tests/conftest.py
- tests/unit/packages/test_base.py
> tests: use a path in the user's home directory for xattrs tests

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add base layer data to ProjectInfo
* Add qmake plugin
* Add proxy support to ant plugin
* Use rustup snap in the Rust plugin
* Update documentation
-----
> Release 1.27.0

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.py
* Add maven plugin documentation
* Add documentation linters
* Rework bundling of shared docs
-----
> Release 1.29.0

- craft_parts/parts.py
- pyproject.toml
- setup.py
- tox.ini
-----
This comes in three commits so the changes are more obvious.
Supersedes #699
> chore: update ruff

- setup.py
- tests/fake_servers.py
- tests/integration/plugins/test_python/setup.py
> build(deps): update pyright to 1.1.358

- docs/Makefile
- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/requirements.txt
> fix(wordlist): add ErrorDict to allowed spelling

- docs/common/craft-parts/reference/plugins/make_plugin.rst
- docs/reference/plugins.rst
> feat(docs): make plugin reference

- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/common/craft-parts/reference/plugins/autotools_plugin.rst
- docs/reference/plugins.rst
> feat(docs): autotools plugin reference

- docs/common/craft-parts/reference/plugins/cmake_plugin.rst
- docs/reference/plugins.rst
> feat(docs): cmake plugin reference

- docs/Makefile
- docs/common/craft-parts/explanation/parts.rst
- docs/common/craft-parts/reference/part_properties.rst
-----
This pull request applies a minor modification to fix the documentation generation.
> fix(docs): adapt to new ifconfig behavior

- docs/common/craft-parts/reference/plugins/dotnet_plugin.rst
- docs/reference/plugins.rst
-----
https://canonical-craft-parts--723.com.readthedocs.build/en/723/common/craft-parts/reference/plugins/dotnet_plugin.html
> docs: document the .NET plugin

- craft_parts/plugins/base.py
- docs/common/craft-parts/reference/plugins/ant_plugin.rst
- docs/common/craft-parts/reference/plugins/maven_plugin.rst
- docs/reference/plugins.rst
-----
https://canonical-craft-parts--722.com.readthedocs.build/en/722/common/craft-parts/reference/plugins/ant_plugin.html
> docs: document the Ant plugin

- craft_parts/plugins/meson_plugin.py
- docs/common/craft-parts/reference/plugins/meson_plugin.rst
- docs/reference/plugins.rst
-----
https://canonical-craft-parts--725.com.readthedocs.build/en/725/common/craft-parts/reference/plugins/meson_plugin.html
> docs: document the Meson plugin

- craft_parts/plugins/__init__.py
- craft_parts/plugins/plugins.py
- tests/unit/plugins/test_plugins.py
-----
Allows applications to unregister a built-in plugin.
> feat: unregister plugins

- .github/workflows/tests.yaml
- Makefile
- setup.py
> chore(lint): use ruff from snap

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/common/craft-parts/craft-parts.wordlist.txt
- setup.py
> build: bump version to 1.30.0

- craft_parts/plugins/base.py
- craft_parts/plugins/meson_plugin.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/common/craft-parts/reference/plugins/ant_plugin.rst
- docs/common/craft-parts/reference/plugins/autotools_plugin.rst
- docs/common/craft-parts/reference/plugins/cmake_plugin.rst
- docs/common/craft-parts/reference/plugins/dotnet_plugin.rst
- docs/common/craft-parts/reference/plugins/go_plugin.rst
- docs/common/craft-parts/reference/plugins/make_plugin.rst
- docs/common/craft-parts/reference/plugins/maven_plugin.rst
- docs/common/craft-parts/reference/plugins/meson_plugin.rst
- docs/common/craft-parts/reference/plugins/nil_plugin.rst
- docs/common/craft-parts/reference/plugins/scons_plugin.rst
- docs/reference/plugins.rst
- docs/requirements.txt
This PR contains all new plugin docs that we've written in the past few weeks; each one has already been individually reviewed, but I rebased this branch on latest `main`.
> New plugin docs

- .github/workflows/tests.yaml
- README.md
- craft_parts/overlays/layers.py
- craft_parts/packages/yum.py
- craft_parts/sources/base.py
- craft_parts/sources/errors.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- tests/unit/sources/test_base.py
- tests/unit/sources/test_errors.py
> fix: add proper error messages (#738)

- docs/common/craft-parts/reference/plugins/qmake_plugin.rst
- docs/reference/plugins.rst
> feat(docs): qmake plugin reference

- craft_parts/packages/apt_cache.py
- craft_parts/packages/deb.py
-----
Partially fixes : #739
Extracted from: #744 
(CRAFT-3010)
> chore: make fetching packages more verbose (#739)

- craft_parts/errors.py
- craft_parts/executor/step_handler.py
- tests/integration/executor/test_errors.py
- tests/unit/test_errors.py
> feat: add docs slug to build exception

- .github/workflows/tests.yaml
- craft_parts/infos.py
- craft_parts/overlays/layers.py
- craft_parts/packages/yum.py
- setup.py
- tests/unit/test_errors.py
> chore: cherry-picks to fix 1.30.1 hotfix branch

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- setup.py
-----
Bump version and update changelog for 1.30.1
> build: bump version to 1.30.1

- docs/conf.py
- tests/integration/plugins/test_autotools.py
> chore: fixes to things linking to the gnu website

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/errors.py
- craft_parts/executor/step_handler.py
- docs/changelog.rst
- setup.py
- tests/integration/executor/test_errors.py
- tests/unit/test_errors.py
The most recent commit, with changelog entries for 1.33.0, is the one that hasn't been reviewed yet.
> Merge `rockcraft` back to `main`

- Makefile
- README.md
> chore: documentation polish

- docs/changelog.rst
- docs/common/craft-parts/craft-parts.wordlist.txt
-----
Release notes for 1.34.0.
Needed for https://github.com/canonical/snapcraft/pull/4945
> docs(changelog): add 1.34.0 release notes

- .github/workflows/tests.yaml
> build(ci): run tests on noble

- craft_parts/lifecycle_manager.py
- craft_parts/utils/partition_utils.py
- tests/unit/features/partitions/executor/test_environment.py
- tests/unit/features/partitions/test_lifecycle_manager.py
- tests/unit/utils/test_partition_utils.py
> feat: allow hyphens in partition names

- craft_parts/plugins/base.py
- craft_parts/plugins/python_plugin.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- tests/unit/plugins/test_base.py
- tests/unit/plugins/test_python_plugin.py
-----
This creates a base Python plugin to allow multiple Python plugins with different build systems.
> feat(plugins): create base Python plugin

- craft_parts/parts.py
- tests/unit/test_parts.py
-----
Fixes the craft-parts part of https://github.com/canonical/snapcraft/issues/4978
> fix(parts): coerce numbers in input model

- .github/workflows/tests.yaml
- craft_parts/plugins/base.py
- craft_parts/plugins/plugins.py
- craft_parts/plugins/poetry_plugin.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- tests/integration/plugins/test_poetry.py
- tests/integration/plugins/test_poetry/pyproject.toml
- tests/integration/plugins/test_poetry/test_poetry/__init__.py
- tests/integration/plugins/test_poetry/test_poetry/__main__.py
- tests/unit/plugins/test_poetry_plugin.py
-----
Fixes #707 
Tests are failing because I'm battling with CI, but passing locally. Reviews requested so you can review while I'm still battling there.
>  feat(plugin): add poetry plugin

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- setup.py
* Fix NPM plugin to be stateless, allowing lifecycle steps to be executed in separate runs
-----
> Release 1.33.1

- craft_parts/plugins/npm_plugin.py
- docs/changelog.rst
- tests/unit/plugins/test_npm_plugin.py
> chore(merge): 'merge-1.33.1' into 'main'

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- setup.py
This can be rebase-merged straight into main
> Prepare 2.1.1 release

- docs/how-to/document-plugin.rst
Put a note that it may be useful to include in app-specific plugins
-----
> docs: remove version from plugin documentation howto

- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/common/craft-parts/reference/plugins/rust_plugin.rst
-----
This pull request updates explanations to reflect changes in newer Rust toolchains and LLVM/Clang tooling (for the contents that describe cross-language optimizations).
> docs(rust_plugin): update explanations to reflect changes in newer Rust toolchains

- .github/workflows/security-scan.yaml
> ci: add security scanning job

- .github/workflows/tests.yaml
- craft_parts/executor/part_handler.py
- craft_parts/lifecycle_manager.py
- craft_parts/overlays/layers.py
- craft_parts/packages/deb.py
- craft_parts/packages/yum.py
- pyproject.toml
- setup.py
- tests/fake_servers.py
- tests/integration/features/partitions/lifecycle/test_lifecycle.py
- tests/integration/lifecycle/test_chisel_lifecycle.py
> Fix 1.25 build

- .bumpversion.cfg
- .github/workflows/tests.yaml
- craft_parts/__init__.py
- docs/changelog.rst
- docs/conf.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/integration/packages/test_snaps.py
> chore: backport unixsocket -> unixsocket2 conversion to 1.19 for snapcraft 7

- .bumpversion.cfg
- craft_parts/__init__.py
- docs/changelog.rst
- docs/requirements.txt
- setup.py
-----
I need to get all the requests-unixsocket2 migrations out the door
> docs(changelog): add 2.1.2 release notes

- docs/changelog.rst
- docs/common/craft-parts/reference/plugins/poetry_plugin.rst
- docs/common/craft-parts/reference/plugins/python_plugin.rst
- docs/tutorials/examples.rst
-----
- Also cherry-picks the docs fixes from #872 
- Includes a fix to make the docs linters pass
> docs(changelog): release 2.1.3

- .bumpversion.cfg
- craft_parts/__init__.py
- setup.py
> build: bump version to 2.1.3

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/plugins/poetry_plugin.py
- docs/changelog.rst
- docs/tutorials/examples.rst
- setup.py
- tests/unit/plugins/test_poetry_plugin.py
> chore(merge): 2.1.3 into main

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/executor/environment.py
- craft_parts/infos.py
- craft_parts/plugins/poetry_plugin.py
- docs/changelog.rst
- docs/conf.py
- pyproject.toml
- setup.py
- tests/unit/plugins/test_poetry_plugin.py
- tests/unit/test_infos.py
The first two commits address unrelated/semi-related linting issues
> fix: expose part deps in PartInfo

- .bumpversion.cfg
- craft_parts/__init__.py
- craft_parts/executor/environment.py
- craft_parts/infos.py
- craft_parts/plugins/poetry_plugin.py
- docs/changelog.rst
- pyproject.toml
- setup.py
- tests/unit/plugins/test_poetry_plugin.py
- tests/unit/test_infos.py
-----
Merge 2.1.4 back into main.
> chore(merge): 2.1.4 into main

- docs/common/craft-parts/reference/plugins/npm_plugin.rst
> link to common part properties

- craft_parts/errors.py
- tests/integration/executor/test_errors.py
> fix: remove captured message on error

- .github/workflows/tests.yaml
- Makefile
- craft_parts/plugins/base.py
- craft_parts/plugins/npm_plugin.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- pyproject.toml
- tests/integration/plugins/test_npm.py
- tests/unit/plugins/test_npm_plugin.py
Implement origin package -> file mapping for the npm plugin, to be used in xattr tagging.
-----
(CRAFT-3742)
> feat: npm plugin file listing

- docs/changelog.rst
- docs/common/craft-parts/craft-parts.wordlist.txt
-----
Lots of features in 2.2.0!
> docs(changelog): add 2.2.0 changes

- craft_parts/packages/platform.py
- tests/unit/packages/test_normalize.py
> style: fix linting issues for ruff 0.9

- docs/reference/changelog.rst
Finalize changelog for 2.4.0 release of `craft-parts`.
> docs(changelog): finalize changelog for 2.4.0

- tests/unit/plugins/test_java_plugin.py
> fix(tests): don't fail if you have additional JREs

- docs/common/craft-parts/reference/part_properties.rst
-----
Error was discovered in https://github.com/canonical/open-documentation-academy/pull/163#discussion_r1933961059
> docs: correct the lifecycle step for `organize`

- craft_parts/sources/__init__.py
- docs/common/craft-parts/reference/plugins/cargo-package.rst
- docs/common/craft-parts/reference/plugins/cargo-package_plugin.rst
- docs/reference/plugins.rst
No changelog entry because this is targeted at a feature branch.
-----
https://canonical-craft-parts--992.com.readthedocs.build/en/992/common/craft-parts/reference/plugins/cargo-package_plugin.html
> docs(reference): cargo-package reference docs

- craft_parts/executor/executor.py
- craft_parts/executor/migration.py
- craft_parts/executor/part_handler.py
- tests/integration/lifecycle/test_lifecycle.py
This adds cleaning to the backstage directory.
I feel like I've missed something because this was way too simple.
CRAFT-3992
-----
https://github.com/canonical/snapcraft/pull/5237
> feat: clean the backstage directory

- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/reference/changelog.rst
> docs: update changelog

- docs/reference/changelog.rst
> Release 2.7.0

- docs/common/craft-parts/how-to/use_parts.rst
It's blocking ingestion in downstream projects.
---
- ~~Have you added an entry to the changelog (`docs/reference/changelog.rst`)?~~
-----
> docs(fix): adjust heading level in 'using parts'

- docs/reference/changelog.rst
> docs(changelog): add changelog for 2.8.0

- pyproject.toml
- uv.lock
> build(deps): update python-apt for plucky

- .gitignore
-----
Sync `.gitignore` from starbase to craft-parts.
> chore(.gitignore): sync with starbase

- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/explanation/cryptography.rst
- docs/explanation/index.rst
-----
Add an [explanation](https://canonical-craft-parts--1073.com.readthedocs.build/en/1073/explanation/cryptography/) of how cryptography is used in craft-parts.
(CRAFT-4394)
> docs: add explanation for cryptography

- docs/common/craft-parts/reuse/links.txt
- docs/conf.py
-----
Fixes some broken links in the documentation.
> docs: update links

- docs/reference/changelog.rst
-----
Add an entry for the 2.11.0 release.
> docs(changelog): finalize 2.11.0

- docs/reference/changelog.rst
-----
Finalizes the 2.14.0 release.
> docs(changelog): finalize 2.14.0

- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/reference/changelog.rst
> docs: finalize changelog for 2.16.0

- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/common/craft-parts/explanation/file-migration.rst
> docs: address minor spellchecking issues

- docs/reference/changelog.rst
> docs: Release 2.18.0

- craft_parts/parts.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- docs/reference/changelog.rst
- tests/fake_servers.py
- tests/integration/features/partitions/lifecycle/test_lifecycle.py
-----
Fix a broken link in docs.
Also fix some minor linting issues with new version of ruff.
> fix: Broken link docs

- craft_parts/executor/environment.py
- craft_parts/infos.py
- craft_parts/utils/partition_utils.py
- docs/reference/changelog.rst
- tests/unit/executor/test_step_handler.py
- tests/unit/features/partitions/executor/test_environment.py
> fix: Set CRAFT_DEFAULT_* env vars when the default partition is aliased

- docs/reference/changelog.rst
-----
Finalize the changelog for a 2.20.0 release.
> docs: finalize 2.20.0

- README.md
-----
Updates README according to the template with strong influence from [Craft Application's](https://github.com/canonical/craft-application/blob/259acbadcf291f3bf47e3e3dfc2d3cebdb1121ef/README.md) current README.
> docs: update README according to template

- craft_parts/infos.py
- docs/common/craft-parts/craft-parts.wordlist.txt
- tests/unit/test_infos.py
-----
Adds a `ProjectVarInfo` class to wrap a nested dictionary of project variables.
This class will be used in a subsequent PR.
(SNAPCRAFT-1050)
> feat(infos): add ProjectVarInfo class

- craft_parts/utils/maven/common.py
- docs/reference/changelog.rst
- pyproject.toml
- tests/unit/utils/test_maven_utils.py
- uv.lock
-----
The logic for this is unfortunately quite messy since I'm dealing with potentially arbitrary strings, but I tried to ensure each code path was documented and had full test coverage. I'm open to adding more tests if some edge cases are thought of.
> feat(maven-use): improve selection when rewriting version numbers

- Makefile
> feat(Makefile): make chisel, go and core20 installs optional

- docs/common/craft-parts/explanation/lifecycle.rst
- docs/common/craft-parts/explanation/overlays.rst
- docs/index.rst
- docs/tutorials/examples.rst
Some of these are also causing frequent lint CI failures
---
> docs: rewrite some redirects

- .github/workflows/qa.yaml
> ci: run Python plugin tests on more platforms

- docs/reference/changelog.rst
> docs: add new Python plugin to the changelog

- docs/reference/changelog.rst
> docs: Release 2.25.0

- docs/common/craft-parts/reference/plugins/python_v2_plugin.rst
---
I accidentally repeated a sentence. I accidentally repeated a sentence.
> docs: deduplicate a sentence
